### ISSUE TITLE
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null exception

### ISSUE THREAD

**Issue by sl-he** [Agoric/agoric-sdk#1037]
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
I[2020-04-30|23:32:52.151] Executed block                               module=state height=36 validTxs=1 invalidTxs=0
I[2020-04-30|23:32:52.192] Committed state                              module=state height=36 txs=1 appHash=98183558ED6B1435555DDB1F0DB1F9EE5407B7B555BE4EBB10C85BF57B6CD5F7
panic: Failed to process committed block (37:A28238E0E478CAF76A68FE4ECF33409295D9338936FD711C2A519F193107073A): wrong Block.Header.AppHash.  Expected 98183558ED6B1435555DDB1F0DB1F9EE5407B7B555BE4EBB10C85BF57B6CD5F7, got E5A7223C0B605358E7B770D4ADBC28E6EB5A9348E143206E6DE4FBAFB765ED53

goroutine 191 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00001c4e0)
        /root/work/pkg/mod/github.com/tendermint/tendermint@v0.33.4/blockchain/v0/reactor.go:349 +0x12ef
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/work/pkg/mod/github.com/tendermint/tendermint@v0.33.4/blockchain/v0/reactor.go:118 +0x86
Aborted (core dumped)

**Comment by warner** [comment]
Thanks for the report! What version of the agoric-sdk were you using?

@michaelfig does this look like at all like the IBC divergence you saw the other day?

**Comment by michaelfig** [comment]
Duplicate of #1044.
