### ISSUE TITLE
Coredumped with initial sync at 35 block

### ISSUE THREAD

**Issue by sl-he** [Agoric/agoric-sdk#1044]
I[2020-05-02|19:32:39.794] Committed state                              module=state height=34 txs=0 appHash=7EAA7AA06A358B5B52C202852CDB3EE400EA29E63C12B75130AFAC257D9AD426
I[2020-05-02|19:32:39.810] Executed block                               module=state height=35 validTxs=0 invalidTxs=0
I[2020-05-02|19:32:39.834] Committed state                              module=state height=35 txs=0 appHash=DECC2CD7733EA91371BB2C991A693A96FB0F6A10E72F393C058ED49C29362983
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
SwingSet: controller: UnhandledPromiseRejectionWarning: TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read property 'receive' of null
    at eval (/bundled-source/eventual-send.cjs.js:535:23)
    at Object.eval [as applyMethod] (/bundled-source/eventual-send.cjs.js:522:18)
    at eval (/bundled-source/eventual-send.cjs.js:571:66)
I[2020-05-02|19:32:39.900] Executed block                               module=state height=36 validTxs=1 invalidTxs=0
I[2020-05-02|19:32:39.909] Committed state                              module=state height=36 txs=1 appHash=98183558ED6B1435555DDB1F0DB1F9EE5407B7B555BE4EBB10C85BF57B6CD5F7
panic: Failed to process committed block (37:A28238E0E478CAF76A68FE4ECF33409295D9338936FD711C2A519F193107073A): wrong Block.Header.AppHash.  Expected 98183558ED6B1435555DDB1F0DB1F9EE5407B7B555BE4EBB10C85BF57B6CD5F7, got E5A7223C0B605358E7B770D4ADBC28E6EB5A9348E143206E6DE4FBAFB765ED53

goroutine 91 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00010d1e0)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/blockchain/v0/reactor.go:349 +0x12ef
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/blockchain/v0/reactor.go:118 +0x86
Aborted (core dumped)

**Comment by michaelfig** [comment]
Not sure yet what's causing this, but it could be solved by the Cosmos SDK fixes we landed in current master.

**Comment by michaelfig** [comment]
Could be related to:
https://github.com/cosmos/cosmos-sdk/issues/6114

**Comment by michaelfig** [comment]
As observed by @dckc, this apparently is due to forgetting to set `$BOOT_ADDRESS`.  Could you please take another look at https://github.com/Agoric/agoric-sdk/wiki/Validator-Guide#syncing-your-node ?
