### ISSUE TITLE
'canvas' sometimes does not compile without 'pixman-1' installed

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1072]
Somewhere in our tree, something is depending upon a Node.js package named [`canvas`](https://www.npmjs.com/package/canvas). Canvas requires a native-code `.so` library, and during install time, canvas either downloads a pre-compiled version from [the collection on github](https://github.com/node-gfx/node-canvas-prebuilt/releases), or falls back to trying to compile the library itself. Compiling this library locally requires another library named [`pixman-1`](https://packages.debian.org/buster/libpixman-1-dev) already be installed on your system. If this is not installed, the initial `yarn` (aka `yarn install`) step fails with a message that buries the following error somewhere in the middle:

```
error /home/warner/stuff/agoric/agoric-sdk/node_modules/canvas: Command failed.
...
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/warner/stuff/agoric/agoric-sdk/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.15.0-99-generic
gyp ERR! command "/home/warner/.nvm/versions/node/v14.1.0/bin/node" "/home/warner/stuff/agoric/agoric-sdk/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/warner/stuff/agoric/agoric-sdk/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/warner/stuff/agoric/agoric-sdk/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/warner/stuff/agoric/agoric-sdk/node_modules/canvas
```

This will happen when GitHub's release-binary webserver has a bad day (which happened today for a few hours), or when you use a platform without pre-built binaries (unlikely, they offer windows/linux/macos flavors), or when you use a version of Node that doesn't have a pre-built binary. I'm still trying to figure out which versions of Node have pre-built binaries available.

If it has to compile, and you're on a debian-like system, `apt-get install libpixman-1-dev` might help.

CC @dtribble who saw this fail on CI, @FUDCo who might be involved in the `canvas` addition, and @michaelfig who didn't run away fast enough :)

**Comment by warner** [comment]
It looks like https://nodejs.org/en/download/releases/ has a table of releases with their ABI version. The collection of pre-built binaries includes ABI versions `[48, 51, 57, 59, 64, 67, 72, 79, 83]`. That ought to cover everything from the ancient Node-v6.0.0 to the most recent (as of today) v14.2.0.

So this is probably only an issue when GitHub is down.

**Comment by katelynsills** [comment]
It looks like canvas is being used in stat-logger by @FUDCo https://github.com/Agoric/agoric-sdk/blob/94e0078673ff15e47c2fcf32f472d27c416a1cd8/packages/stat-logger/package.json#L19. Maybe this issue can be closed?

**Comment by FUDCo** [comment]
Yes, canvas is used by stat-logger, to generate graphs.
