### ISSUE TITLE
Bug: Serialization error swallowed during deploy

### ISSUE THREAD

**Issue by kumavis** [Agoric/agoric-sdk#1266]
**Describe the bug**
as witnessed when pairing with @michaelfig,
a serialization error was swallowed. the following error occured but did not appear in shell
  Error: cannot serialize objects with non-methods

**To Reproduce**
heres the snap dragon project
https://github.com/kumavis/agoric-sdk/tree/6f50c6a3a535ce99964cbdedd117d803127e227a/packages/snap-dragon
- change `demo-snap/snap-hello.js` to have an invalid api surface
- run `agoric deploy demo-snap/deploy.js`
- the process will not complete (no error, no abort, hangs)

**Expected behavior**
should error and exit with non-zero exit code

**Comment by michaelfig** [comment]
Tested against the latest `agoric-sdk`, and we now get this kind of error on the console:
```js
agoric: [Error <Object <[Object: null prototype] {}>>: cannot serialize objects with non-methods like the .source in [object Object]
  at /Users/michael/agoric/agoric-sdk/packages/marshal/marshal.js:248:13
  at Array.forEach (<anonymous>)
  at assertCanBeRemotable (/Users/michael/agoric/agoric-sdk/packages/marshal/marshal.js:246:9)
  at mustPassByRemote (/Users/michael/agoric/agoric-sdk/packages/marshal/marshal.js:265:5)
  at passStyleOf (/Users/michael/agoric/agoric-sdk/packages/marshal/marshal.js:333:7)
  at Array.replacer (/Users/michael/agoric/agoric-sdk/packages/marshal/marshal.js:456:25)
  at JSON.stringify (<anonymous>)
  at serialize (/Users/michael/agoric/agoric-sdk/packages/marshal/marshal.js:544:18)
  at Object.applyMethod (/Users/michael/agoric/agoric-sdk/packages/captp/lib/captp.js:157:19)
  at Object.applyMethod (/Users/michael/agoric/agoric-sdk/packages/eventual-send/src/index.js:369:43)]
```

This is as expected, so I'm closing this issue.  Thanks for reporting!
