### ISSUE TITLE
Returning embedded promise from HTTP handler causes device panic

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#1358]
**Describe the bug**

`suggestNewIssuer` causes a kernel panic when we refresh the dapp-encouragement app after making an offer. 

**To Reproduce**
In the `simple-wallet` branch (of both agoric-sdk and dapp-encouragement):
1. start the dapp
2. enable it in the wallet
3. submit an offer for an encouragement
4. refresh the dapp-encouragement webpage

**Expected behavior**
The refresh succeeds

**Platform Environment**
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

hackathon-2020-07-227-gb8716d53

**Details**

```
tribble@Alien:~/git/dapp-encouragement$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: setting sim chain with 0 second delay
Circular dependency: ../../../../agoric-sdk/packages/notifier/src/notifier.js -> ../../../../agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js -> ../../../../agoric-sdk/packages/notifier/src/notifier.js
Circular dependency: ../../../../agoric-sdk/packages/notifier/src/notifier.js -> ../../../../agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js -> ../../../../agoric-sdk/packages/notifier/src/notifier.js
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
Circular dependency: ../../../../agoric-sdk/packages/notifier/src/notifier.js -> ../../../../agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js -> ../../../../agoric-sdk/packages/notifier/src/notifier.js
Circular dependency: ../../../../agoric-sdk/packages/notifier/src/notifier.js -> ../../../../agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js -> ../../../../agoric-sdk/packages/notifier/src/notifier.js
start: swingset running
SwingSet: controller: UnhandledPromiseRejectionWarning: Error <Object <[Object: null prototype] {}>>: disconnected from "http://localhost:8000"
    at Error (/mnt/c/dev/git/agoric-sdk/packages/tame-metering/src/tame.js:119:18)
    at Error (/mnt/c/dev/git/agoric-sdk/node_modules/ses/dist/ses.cjs:2873:14)
    at abort (vat-http/agoric-sdk/packages/captp/lib/captp.js:307:15)
    at Object.onClose (vat-http/dapp-encouragement/_agstate/agoric-servers/dev/vats/captp.js:28:30)
    at /mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:425:23
    at Object.applyMethod (/mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:410:14)
    at win (/mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:442:52)
    at /mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:459:20
SwingSet: controller: UnhandledPromiseRejectionWarning: Error <Object <[Object: null prototype] {}>>: disconnected from "http://localhost:8000"
    at Error (/mnt/c/dev/git/agoric-sdk/packages/tame-metering/src/tame.js:119:18)
    at Error (/mnt/c/dev/git/agoric-sdk/node_modules/ses/dist/ses.cjs:2873:14)
    at abort (vat-http/agoric-sdk/packages/captp/lib/captp.js:307:15)
    at Object.onClose (vat-http/dapp-encouragement/_agstate/agoric-servers/dev/vats/captp.js:28:30)
    at /mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:425:23
    at Object.applyMethod (/mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:410:14)
    at win (/mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:442:52)
    at /mnt/c/dev/git/agoric-sdk/packages/eventual-send/src/index.js:459:20
SwingSet: kernel: ##### KERNEL PANIC: error during syscall/device.invoke: Error: devices cannot import Promises #####
SwingSet: kernel: syscall suffered error, shutdown commencing
web: 127.0.0.1:54946[11]: inbound error: syscall suffered error, shutdown commencing from {
  "type": "walletSuggestIssuer",
  "petname": "Assurance",
  "boardId": "3715714",
  "dappOrigin": "http://localhost:3000",
  "suggestedDappPetname": "Encouragement",
  "meta": {
    "channelID": 11,
    "origin": "http://localhost:8000",
    "url": "/private/wallet-bridge",
    "date": 1596252640887
  }
}
web: 127.0.0.1:54946[11]: inbound error: Error <Object <[Object: null prototype] {}>>: devices cannot import Promises
    at mapKernelSlotToDeviceSlot (kernel/packages/SwingSet/src/kernel/state/deviceKeeper.js:104:15)
    at eval (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:42)
    at Array.map (<anonymous>)
    at Array.map (/mnt/c/dev/git/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
    at Object.kernelInvocationToDeviceInvocation (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:30)
    at invoke (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:48:32)
    at Object.doKernelSyscall (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:163:16)
    at vatSyscallHandler (kernel/packages/SwingSet/src/kernel/kernel.js:577:43)
    at doSyscall (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:80:18)
    at Object.callNow (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:100:27) from {
  "type": "walletSuggestIssuer",
  "petname": "Assurance",
  "boardId": "3715714",
  "dappOrigin": "http://localhost:3000",
  "suggestedDappPetname": "Encouragement",
  "error": "\"syscall suffered error, shutdown commencing\"",
  "meta": {
    "channelID": 11,
    "dispatcher": "onError",
    "origin": "http://localhost:8000",
    "url": "/private/wallet-bridge",
    "date": 1596252641428
  }
}
SwingSet: controller: UnhandledPromiseRejectionWarning: Error <Object <[Object: null prototype] {}>>: devices cannot import Promises
    at mapKernelSlotToDeviceSlot (kernel/packages/SwingSet/src/kernel/state/deviceKeeper.js:104:15)
    at eval (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:42)
    at Array.map (<anonymous>)
    at Array.map (/mnt/c/dev/git/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
    at Object.kernelInvocationToDeviceInvocation (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:30)
    at invoke (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:48:32)
    at Object.doKernelSyscall (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:163:16)
    at vatSyscallHandler (kernel/packages/SwingSet/src/kernel/kernel.js:577:43)
    at doSyscall (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:80:18)
    at Object.callNow (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:100:27)
SwingSet: controller: UnhandledPromiseRejectionWarning: Error <Object <[Object: null prototype] {}>>: devices cannot import Promises
    at mapKernelSlotToDeviceSlot (kernel/packages/SwingSet/src/kernel/state/deviceKeeper.js:104:15)
    at eval (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:42)
    at Array.map (<anonymous>)
    at Array.map (/mnt/c/dev/git/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
    at Object.kernelInvocationToDeviceInvocation (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:30)
    at invoke (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:48:32)
    at Object.doKernelSyscall (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:163:16)
    at vatSyscallHandler (kernel/packages/SwingSet/src/kernel/kernel.js:577:43)
    at doSyscall (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:80:18)
    at Object.callNow (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:100:27)
SwingSet: controller: UnhandledPromiseRejectionWarning: Error <Object <[Object: null prototype] {}>>: devices cannot import Promises
    at mapKernelSlotToDeviceSlot (kernel/packages/SwingSet/src/kernel/state/deviceKeeper.js:104:15)
    at eval (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:42)
    at Array.map (<anonymous>)
    at Array.map (/mnt/c/dev/git/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
    at Object.kernelInvocationToDeviceInvocation (kernel/packages/SwingSet/src/kernel/deviceTranslator.js:24:30)
    at invoke (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:48:32)
    at Object.doKernelSyscall (kernel/packages/SwingSet/src/kernel/kernelSyscall.js:163:16)
    at vatSyscallHandler (kernel/packages/SwingSet/src/kernel/kernel.js:577:43)
    at doSyscall (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:80:18)
    at Object.callNow (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:100:27)```

**Comment by michaelfig** [comment]
Found it: updatAllInboxState was returning an array of promises, which started off empty.

When it contained a promise, then awaiting the array would still result in an array of promise, crashing the kernel when returning it from the web request.  Wrapping the array in Promise.all gave the right behaviour.

**Comment by michaelfig** [comment]
This still shouldn't have caused a panic.  Reopening.

**Comment by warner** [comment]
I think this is a consequence of two design choices:

* Devices don't do promises, for all the reasons described in #1346 . They "don't do promises" so hard that they can't even deserialize a promise you send to them. It causes an exception in `deviceSlots`, which is within the vat (device) boundary but before the vat (device) code gets a chance to run
* Devices are invoked synchronously, and a successful return value is serialized on one side, then deserialized back into the calling vat. During the latest refactoring (#1339), I decided the new device invocation API should not attempt to serialize exceptions in the same way (I don't think we want to have exceptions as part of the normal device API flow), and instead I declared that errors in device invocation are just as fatal as errors in the kernel itself.

https://github.com/Agoric/agoric-sdk/blob/b2c980a8a82eda68f178a235de0ad04ca45b275b/packages/SwingSet/src/kernel/kernel.js#L575-L593

I think it might be easier to manage this if we implement #1346, which would allow devices to interact with promises again, at the cost of needing to write them at a lower level (we'd get rid of DeviceSlots, and device code would work with raw object/promise/devicenode reference strings). We'd retain the rule that devices must never throw (that'd still be a kernel-fatal error), but devices could return `['error', reason]` and we could deliver this all the way through to the calling vat, where liveSlots could maybe `throw` something.

The deeper question is how isolated we make devices. We trap exceptions in vats, and reject the result promise, but we're still on the fence as to whether we want to encourage exceptions are part of a normal API, or if they're unusual enough (and unlikely to be caught usefully by calling code) that we should alert somebody when they happen (because they probably indicate an error, and if the caller isn't paying attention, then dropping it on the floor will make things hard to debug). More serious errors (referencing missing imports, resolving promises you don't own) are vat-fatal, but we only plan to survive that when it happens in a "user" vat (contract instance), not a long-lived static service vat that we wrote.

We could do the same with devices, but we aren't going to have any disposable "user" devices: the handful of devices we ever use will all be written by us, and if one breaks, we can't really continue. There might be a subset of errors which are survivable, but how would we tell the difference? How much work did the device do before it experienced the error? What state was it left in?

So I'm inclined to think that device errors should continue to be fatal. Until #1346 is done, that means we must protect device nodes from hostile code (which could kill everything by sending a non-unserializable promise).

**Comment by FUDCo** [comment]
It seems to me that there are errors and then there are errors.  It make sense for an error stemming from a malformed device invocation (i.e., the caller did something wrong and needs to be fixed) to be fatal, but not for an error resulting from some kind of recoverable problem that is internal to the device itself but which needs to be signaled to the caller -- though perhaps the latter don't count as "errors" in the world model being discussed here?

Also, an error that kills the invoking vat is a different creature from an error that kills the swingset.  Having an instance of the former cause a kernel panic is a lurking and possibly serious availability problem.

**Comment by warner** [comment]
> Also, an error that kills the invoking vat is a different creature from an error that kills the swingset. Having an instance of the former cause a kernel panic is a lurking and possibly serious availability problem.

For sure, user vats should never ever be able to kill the swingset, nor should they be able to kill/damage any device, nor a static vat, since everything in the system depends upon those items. Our usual rules about defensive consistency apply: a misbehaving customer should not prevent our TCB from providing good service to the well-behaved customers.

In the current "no promises" device model, we implement that by having device nodes be closely-held by defensive companion vats. I think we're doing that correctly, however 1: it's annoying (vat+device instead of just device), and 2: sometimes the companion vats have bugs too, which I think is what this crash was triggered by.

**Comment by michaelfig** [comment]
I'd like to see device promises deserialized as just empty objects, as they would be with JSON.  Solves this crash, and would be reasonably predictable.  Add a property like `__promise_p+29__elided__` and we're good to go.

**Comment by warner** [comment]
I don't understand how that would avoid the crash.. the problem here is that the device c-list rejects an attempt to populate an entry that points to a promise. It sounds like the HTTP vat was invoking the Command device to send some data, and accidentally included a Promise in that data. The vat's liveslots dutifully serialized the promise as a `p+NN` reference, but then the device translator rejected the reference because devices don't do promises.

If we move to the #1346 -style approach, the Command device would receive some data with some slots. It would probably reject any message that had any slots at all, because it's expecting to receive plain data (that it can return to the HTTP request, or emit on the websocket or whatever). The device would still be invoked, though, and it'd still have a chance to react to the problem more gently than crashing. Actually, with #1346 we'd probably have the HTTP vat do a regular message send to the device, not a device invocation, since the response doesn't have to be immediate. Which means we can use a promise rejection as the error pathway, like a normal vat.

**Comment by warner** [comment]
The short term fix for this is for the "translator" (which converts vat-relative slots to kernel-relative slots) for the `callNow` syscall to reject promises in the arguments. If a vat tries to do that, the error will be attributed to the calling vat, rather than the kernel or the device. That will kill the calling vat, which makes the system nearly as useless as if the kernel or device had paniced, but it's incrementally better and makes the authority relationships more correct.

**Comment by FUDCo** [comment]
Unlike some of these translation errors (such as referring to an invalid vatID) that can only occur due to a bad liveslots layer or a badly misbehaving vat, it seems like this one could be triggered by an ordinary programming error in the vat code.  Why not just throw it back to the vat as a TypeError and hand responsibility for dealing with it to the vat developer through the normal debugging process?

**Comment by warner** [comment]
That's a good idea, although I'm thinking it should be done in addition to the translator-level change. The additional fix would go into liveslots, changing the `D()` function to serialize the arguments and then examine the slots for promises, throwing an exception if one was found. That would reject the one call, but save the vat as a whole.

I've got a PR ready to submit that adds the translator layer. I'll start on a second one which adds the liveslots catch.
