### ISSUE TITLE
Syntax Error when running `agoric start --reset`

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2046]
**To Reproduce**
1. check out https://github.com/ski/umqhele ; in particular, version 6d9eb25e9123
2. `agoric install`
    - some number `yarn install` and `agoric deploy` in `contract`, `api`, and `ui` that I don't recall exactly.
3. `agoric start --reset`

```
~/projects/umqhele$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: rm -rf _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake --webport=8000
agoric: start: setting sim chain with 0 second delay
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo set-fake-chain --delay=0 sim-chain
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo start
error running ag-solo: (SyntaxError#1)

  SyntaxError#1: Unexpected character '' (1:0)
     at Parser.raise (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/parser/location.js:27:17)
    at Parser.getTokenFromCode (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/tokenizer/index.js:644:10)
    at Parser.nextToken (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/tokenizer/index.js:144:12)
    at Parser.parse (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/parser/index.js:38:10)
    at parse (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/index.js:44:38)
    at transform (/home/connolly/projects/agoric/ag-sdk-orb/packages/transform-eventual-send/src/index.js:8:38)
    at Object.transform (/home/connolly/projects/agoric/ag-sdk-orb/packages/bundle-source/src/index.js:25:15)
    at Function.apply (/home/connolly/projects/agoric/ag-sdk-orb/packages/tame-metering/src/tame.js:172:20)
    at /home/connolly/projects/agoric/ag-sdk-orb/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:13117:25
  
Maybe the chain has bumped and you need to rerun ag-setup-solo?
```

**Expected behavior**
ag-solo starts up and listens on 8080 as usual

**Platform Environment**
 - what OS are you using? what version of Node.js?
linux
`node --version` v14.15.0

 - is there anything special/unusual about your platform?
no?

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

$ git describe --tags --always
@agoric/acorn-eventual-send@2.0.10-36-gc5092680

**Comment by dckc** [comment]
switching to master seems to make the symptoms go away...

```
connolly@jambox:~/projects/agoric/ag-sdk-orb$ git fetch
...
From https://github.com/Agoric/agoric-sdk
   c5092680..7aedb3fd  hackathon-2020-11 -> upstream/hackathon-2020-11
   9d094908..fb40b321  master            -> upstream/master
connolly@jambox:~/projects/agoric/ag-sdk-orb$ git checkout master
connolly@jambox:~/projects/agoric/ag-sdk-orb$ git pull upstream master
Updating 4279a993..fb40b321
...

connolly@jambox:~/projects/agoric/ag-sdk-orb$ yarn install && yarn build
```

and lo...

```
connolly@jambox:~/projects/umqhele$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: rm -rf _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake --webport=8000
agoric: start: setting sim chain with 0 second delay
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo set-fake-chain --delay=0 sim-chain
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo start
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
agoric: deploy: running /home/connolly/projects/agoric/ag-sdk-orb/packages/dapp-svelte-wallet/api/deploy.js
```

**Comment by dckc** [comment]
it continues to work when I switch back to the hackathon branch:

```
connolly@jambox:~/projects/agoric/ag-sdk-orb$ git checkout hackathon-2020-11
Switched to branch 'hackathon-2020-11'
...

connolly@jambox:~/projects/agoric/ag-sdk-orb$ git pull
Updating c5092680..7aedb3fd

connolly@jambox:~/projects/agoric/ag-sdk-orb$ yarn install && yarn build
```

and it works:

```
connolly@jambox:~/projects/umqhele$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: rm -rf _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake --webport=8000
agoric: start: setting sim chain with 0 second delay
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo set-fake-chain --delay=0 sim-chain
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo start
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
```

**Comment by dckc** [comment]
oops... forgot to cc @katelynsills @michaelfig @ski

**Comment by michaelfig** [comment]
> it continues to work when I switch back to the hackathon branch:

Hmm.  I tried to reproduce with the exact revisions you originally had and wasn't able to make it fail in that way.

When I've come across these kinds of issues, it's almost always due to the `esm` module cache.  We've solved some of this for the Agoric SDK, in https://github.com/Agoric/agoric-sdk/pull/2021 .  For now, you can also try:

```sh
export ESM_DISABLE_CACHE=true
```

This is really annoying, and similar problems have bitten nearly everybody at Agoric, so I'm not surprised if it's what bit you too.  `-resm` is great when it works, but sometimes it doesn't.

I think we really have to release something like a custom fork named `@agoric/esm` since the `esm` maintainer seems to be preoccupied.

Feel free to add more details if you run into something similar that isn't resolved with setting that environment variable.
