### ISSUE TITLE
`yarn test` fails with "Cannot write messages to v1: write EPIPE" in packages/xsnap

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2301]
Reproducible on my system.

```
workers › worker › xs vat manager

  Rejected promise returned by test. Reason:

  Error {
    message: 'Cannot write messages to v1: write EPIPE',
  }

  › Socket.<anonymous> (/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/xsnap/src/node-stream.js:36:20)
  › emitErrorNT (internal/streams/destroy.js:106:8)
  › emitErrorCloseNT (internal/streams/destroy.js:74:3)



  Uncaught exception in test/workers/test-worker.js

  Error: spawn /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/xsnap/build/bin/mac/release/xsnap ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

  › Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
  › onErrorNT (internal/child_process.js:465:16)

  ─

  1 test failed
  12 known failures
  1 uncaught exception
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/markmiller/.nvm/versions/node/v14.15.3/bin/node
Arguments: /Users/markmiller/src/ongithub/agoric/agoric-sdk/.yarn/releases/yarn-1.22.5.js run test
Directory: /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/SwingSet
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by erights** [comment]
This was an unnoticed consequence of a transient failure to build xsnap. Closing.
