### ISSUE TITLE
Possible bug in Virtual Objects

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2533]
## Describe the bug
https://github.com/Agoric/agoric-sdk/pull/2526 makes payments virtual objects. I think I'm doing everything right, but in the one test that is in a vat, I get an error in the bowels of SwingSet (printed below). I did notice that we are testing [the identity of payments in issuer.js](https://github.com/Agoric/agoric-sdk/blob/55bdaf75df70d6942a8c839bf262adfe17689b66/packages/ERTP/src/issuer.js#L163-L170) so that needs to be changed, but I think that should not produce this error. 

```
Temporary logging of sent error (Error#1)
Nested error
  Error#1: syscall vatstoreSet suffered error, shutdown commencing
     at doSyscall (packages/SwingSet/src/kernel/vatManager/syscall.js:88:13)
    at Object.vatstoreSet (packages/SwingSet/src/kernel/vatManager/syscall.js:104:31)
    at Object.delete (packages/SwingSet/src/kernel/virtualObjectManager.js:303:19)
    at eval (packages/ERTP/src/issuer.js:175:53)
    at Array.forEach (<anonymous>)
    at reallocate (packages/ERTP/src/issuer.js:175:14)
    at eval (packages/ERTP/src/issuer.js:250:29)
    at eval (packages/eventual-send/src/track-turns.js:64:18)
  
  Error#1 ERROR_NOTE: Thrown from: (Error#2) : 2 . 0
  Error#1 ERROR_NOTE: Rejection from: (Error#3) : 13 . 0
  Error#1 ERROR_NOTE: Sent as error:liveSlots:v2#1
  Nested 2 errors under Error#1
    Error#2: Event: 1.1
       at Object.trackTurns (packages/eventual-send/src/track-turns.js:47:24)
      at Function.E.when (packages/eventual-send/src/E.js:102:47)
      at Alleged: moola issuer.split (packages/ERTP/src/issuer.js:241:23)
    
    Error#3: Event: 12.1
       at Object.deliver (packages/SwingSet/src/kernel/liveSlots.js:480:28)
      at eval (packages/SwingSet/src/kernel/vatManager/deliver.js:51:48)
    
##### KERNEL PANIC: kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"name\":\"Error\",\"message\":\"vat terminated\"}","slots":[]} #####
  swingsetTests › splitPayments › splitPayments › test splitPayments

  Rejected promise returned by test. Reason:

  Error {
    message: 'kernel panic kp40.policy panic: rejected {"body":"{\\"@qclass\\":\\"error\\",\\"name\\":\\"Error\\",\\"message\\":\\"vat terminated\\"}","slots":[]}',
  }

  › panic (packages/SwingSet/src/kernel/kernel.js:260:26)
  › doResolve (packages/SwingSet/src/kernel/kernel.js:332:9)
  › resolveToError (packages/SwingSet/src/kernel/kernel.js:338:5)
  › terminateVat (packages/SwingSet/src/kernel/kernel.js:354:9)
  › processQueueMessage (packages/SwingSet/src/kernel/kernel.js:573:9)
  › async Object.run (packages/SwingSet/src/kernel/kernel.js:926:7)
  › async main (packages/ERTP/test/swingsetTests/splitPayments/test-splitPayments.js:9:3)
  › async packages/ERTP/test/swingsetTests/splitPayments/test-splitPayments.js:21:16

```

## To Reproduce
1. Check out branch `1830-ERTP-virtual-objects-payments`
2. `yarn install` and `yarn build` at root
3. `cd packages/ERTP` and `yarn test -m "test splitPayments"`

## Expected behavior
The test should pass.

**Comment by FUDCo** [comment]
Closed by #2539
