### ISSUE TITLE
zoe tests failing on xsnap: SEGV, bad plan, instance not found

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2605]
## Describe the bug

#2573 has us running some zoe tests on XS / xsnap, but it fell short of the mark from #370 in several ways.

The `test:xs-worker` step, i.e. `WORKER_TYPE=xs-worker ava` was postponed altogether. (#2837)

And a number of unit tests are excluded:

```
  "ava-xs": {
    "exclude": [
      "# eek! SIGSEGV in GC https://github.com/Moddable-OpenSource/moddable/issues/592",
      "test-loan-e2e.js",
      "# another SEGV, but not in --debug so I cannot get a stack trace",
      "contracts/test-callSpread-calculation",
      "# another SEGV; not investigated",
      "loan/test-borrow.js",
      "test-fakePriceAuthority.js",
      "test-offerSafety",
      "test-scriptedOracle",
      "test-zoeHelpers",
      "# multiple instances of automaticRefund for the same Zoe bad plan: 6 still to go",
      "test-automaticRefund",
      "test-secondPriceAuction.js",
      "test-escrowToVote",
      "test-coveredCall",
      "# offerOk threw: \"instance\" not found: (an object)'",
      "test-otcDesk.js",
```
 -- https://github.com/Agoric/agoric-sdk/blob/master/packages/zoe/package.json#L75-L93

## To Reproduce
1. In `packages/zoe` remove any of the items above from the ava-xs.exclude list
2. `yarn test:xs-unit`
3. See failed test

Actually, some of these are tricky to reproduce; sometimes they only seem to fail in ci.

## Platform Environment
 - ci runs on linux; some of the tests fail on macOS; some do not

## References

https://github.com/Moddable-OpenSource/moddable/issues/592
https://github.com/Moddable-OpenSource/moddable/issues/604

**Comment by dckc** [comment]
@warner the XS weakmap fix is available as https://github.com/Agoric/agoric-sdk/pull/2607/commits/71037131c17b2bad70613dd8db1cee5954705120

**Comment by dckc** [comment]
@katelynsills did a bunch of work to reduce the size of the code involved in the `yarn test:xs-unit test/test-automaticRefund.js` failure. (Thanks!)
https://github.com/Agoric/agoric-sdk/tree/minimal-automatic-refund-failing-xs 7ae71c1

But it doesn't fail when I run it... quite likely because of the weakmap fix 7103713

**Comment by katelynsills** [comment]
Talked to @dckc privately about this, but just to record it here: I got the same failing tests for automaticRefund on agoric-sdk master with the latest xs, so I think we need to take the minimal branch (https://github.com/Agoric/agoric-sdk/tree/minimal-automatic-refund-failing-xs) and use the incremental commits in that branch to go from failing on agoric-sdk master to failing on something more minimal. Even though the latest commit on that branch passes, there should be prior commits that still fail, even if they aren't as "minimal."

**Comment by dckc** [comment]
collecting CI runs with XS SIGSEGV's:
https://github.com/Agoric/agoric-sdk/runs/2124123807 e6a0924

**Comment by dckc** [comment]
All the zoe XS tests are passing in the last few CI runs that I've seen.

It started with some PR... I don't recall which just now... and I think it was only tangentially related...

**Comment by dckc** [comment]
Darn it... `test-offerSafety.js` still crashes: https://gist.github.com/dckc/6326f06d880ece0866e4e798a24ccaa9

found while trying to prune the exclude list in `packages/zoe/package.json`.

**Comment by dckc** [comment]
## cannot reproduce on GCE

@warner suggested reproducing the problem on a cloud VM that we could share with moddable. I tried without luck.

My workstation has 16GB RAM vs 4GB in GCE. And the CPUs are different in some details, though they are both Intel CPUs.

```
connolly@jambox:~/projects/agoric/agoric-sdk/packages/zoe$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        9.4G        3.3G        741M        2.8G        5.6G
Swap:          7.9G        3.4G        4.5G
```

```
dckc@xsnap1:~/agoric-sdk$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        186M        2.2G        3.5M        1.4G        3.4G
Swap:            0B          0B          0B
```

```
connolly@jambox:~/projects/agoric/agoric-sdk/packages/zoe$ diff -u jambox-cpu.txt gce-cpu.txt 
--- jambox-cpu.txt	2021-04-02 10:08:29.813613886 -0500
+++ gce-cpu.txt	2021-04-02 10:08:57.869708135 -0500
@@ -1,28 +1,27 @@
 processor       : 0
 vendor_id       : GenuineIntel
 cpu family      : 6
-model           : 158
-model name      : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
-stepping        : 9
-microcode       : 0xde
-cpu MHz         : 3070.257
-cache size      : 6144 KB
+model           : 63
+model name      : Intel(R) Xeon(R) CPU @ 2.30GHz
+stepping        : 0
+microcode       : 0x1
+cpu MHz         : 2299.998
+cache size      : 46080 KB
 physical id     : 0
-siblings        : 4
+siblings        : 2
 core id         : 0
-cpu cores       : 4
+cpu cores       : 1
 apicid          : 0
 initial apicid  : 0
 fpu             : yes
 fpu_exception   : yes
-cpuid level     : 22
+cpuid level     : 13
 wp              : yes
-flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
-bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds
-bogomips        : 6799.81
+flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
+bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
+bogomips        : 4599.99
 clflush size    : 64
 cache_alignment : 64
-address sizes   : 39 bits physical, 48 bits virtual
+address sizes   : 46 bits physical, 48 bits virtual
 power management:
```

## cannot replay rr trace on VM

Evidently rr doesn't get along well with VMs, which have software events.

https://github.com/rr-debugger/rr/issues/1610

```
dckc@xsnap1:~/agoric-sdk$ perf list

List of pre-defined events (to be used in -e):

  alignment-faults                                   [Software event]
  bpf-output                                         [Software event]
  context-switches OR cs                             [Software event]
  cpu-clock                                          [Software event]
  cpu-migrations OR migrations                       [Software event]
  dummy                                              [Software event]
  emulation-faults                                   [Software event]
  major-faults                                       [Software event]
  minor-faults                                       [Software event]
  page-faults OR faults                              [Software event]
  task-clock                                         [Software event
```

**Comment by dckc** [comment]
another crash in ci: `test/unitTests/test-testHelpers.js`
https://github.com/Agoric/agoric-sdk/pull/2792/checks?check_run_id=2255007314 68af961 from #2792

It also crashes on my workstation and under rr, so I have another trace: xsnap-8.

```
~/projects/agoric/agoric-sdk/packages/zoe
11:57 connolly@jambox$ XSNAP_DEBUG_RR=1 yarn test:xs-unit --debug test/unitTests/test-testHelpers.js
yarn run v1.22.5
$ ava-xs --verbose --debug test/unitTests/test-testHelpers.js
[Object: null prototype] {}
# test script: test/unitTests/test-testHelpers.js
Module level directives cause errors when bundled, 'use jessie' was ignored.
XSNAP_DEBUG_RR {
  bin: 'rr',
  args: [
    '/home/connolly/projects/agoric/agoric-sdk/packages/xsnap/build/bin/lin/debug/xsnap',
    '<unnamed xsnap worker>'
  ]
}
rr: Saving execution to trace directory `/home/connolly/.local/share/rr/xsnap-8'.
. test/unitTests/test-testHelpers.js assertAmountsEqual - Nat dup
. test/unitTests/test-testHelpers.js assertAmountsEqual - Nat manual
. test/unitTests/test-testHelpers.js assertAmountsEqual - false Nat
(Error#1)
Error#1: <unnamed xsnap worker> exited due to signal SIGSEGV

  at ChildProcess.<anonymous> (packages/xsnap/src/xsnap.js:113:22)
  at ChildProcess.emit (events.js:315:20)
  at ChildProcess.EventEmitter.emit (domain.js:467:12)

error Command failed with exit code 1.
```

**Comment by dckc** [comment]
I'm reducing the scope of this to exclude `test:xs-worker` and postponing metering on xs-worker as its own issue: #2837

**Comment by dckc** [comment]
I'm pretty sure this is done but I'm struggling to land #2788 ; the tests timed out in the last ci run. I just rebased to current master once more...
