### ISSUE TITLE
Phase 2 Agoric Testnet "agorictest-9" is crashing

### ISSUE THREAD

**Issue by pkrasam** [Agoric/agoric-sdk#2903]
Phase 2 Agoric Testnet is crashing here...
```
Apr 16 17:18:51 ag-chain-cosmos[663]: panic: StoreBlockHeight (295227) > StateBlockHeight + 1 (1)
Apr 16 17:18:51 ag-chain-cosmos[663]: goroutine 36 [running]:
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000eca6b0, 0xb, 0x0, 0x0, 0x0, 0xc0010f8eb0, 0xc, 0x4813b, 0x0, 0x0, ...)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:382 +0x162b
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000eca6b0, 0x7f88c740a740, 0xc00061e4e0, 0xc00140fa50, 0x0)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:268 +0x478
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/tendermint/tendermint/node.doHandshake(0x7f88c7406760, 0xc00140e290, 0xb, 0x0, 0x0, 0x0, 0xc0010f8eb0, 0xc, 0x4813b, 0x0, ...)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/node/node.go:293 +0x1d8
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/tendermint/tendermint/node.NewNode(0xc000feb040, 0x7f88c73e8160, 0xc0000e54a0, 0xc00140ed60, 0x7f88c73b2ca0, 0xc000519aa0, 0xc00140edd0, 0x7f88c737c808, 0xc00140eee0, 0x7f88c73f1ae0, ...)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/node/node.go:700 +0x1e25
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0011ce7e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f88c73f99a0, 0xc0004eeb30, ...)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:244 +0x565
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001180280, 0xc001214670, 0x0, 0x1, 0x0, 0x0)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:120 +0x169
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/spf13/cobra.(*Command).execute(0xc001180280, 0xc001214660, 0x1, 0x1, 0xc001180280, 0xc001214660)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000fc8c80, 0x0, 0x0, 0xc001113c20)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/spf13/cobra.(*Command).Execute(...)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000fc8c80, 0xc001113c20, 0x1d, 0xc0004f29e0, 0x7f88c740bf00)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/cmd/execute.go:36 +0x265
Apr 16 17:18:51 ag-chain-cosmos[663]: github.com/Agoric/agoric-sdk/golang/cosmos/daemon.RunWithController(0xc00112d300)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/agoric-sdk/golang/cosmos/daemon/main.go:63 +0x79
Apr 16 17:18:51 ag-chain-cosmos[663]: main.RunAgCosmosDaemon.func2(0xc00112d300)
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:67 +0x2d
Apr 16 17:18:51 ag-chain-cosmos[663]: created by main.RunAgCosmosDaemon
Apr 16 17:18:51 ag-chain-cosmos[663]:         /home/agoric/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:64 +0x137
```

**Comment by Tartuffo** [comment]
Ancient.
