### ISSUE TITLE
Node 16 Error: re2 fails to build

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2977]
## Describe the bug
`yarn install` errors in agoric-sdk using Node 16. See below for the log.

## To Reproduce
1. install Node 16
2. on agoric-sdk master, try `yarn install`

## Expected behavior
This should succeed and not error. 

## Platform Environment
 - what OS are you using? MacOS 11.2.3 (20D91)
 - is there anything special/unusual about your platform? Nope
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) agoricdev-2-116-g3588c2d8d

## Additional context

```
katesills@kates-mbp agoric-sdk % nvm use 16
Now using node v16.0.0 (npm v7.10.0)
katesills@kates-mbp agoric-sdk % yarn install
yarn install v1.22.5
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > eslint-config-airbnb-base@14.0.0" has incorrect peer dependency "eslint@^5.16.0 || ^6.1.0".
warning " > eslint-plugin-import@2.20.0" has incorrect peer dependency "eslint@2.x - 6.x".
warning " > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
warning " > @agoric/ui-components@0.2.6" has unmet peer dependency "@material-ui/core@^4.11.3".
warning " > @agoric/ui-components@0.2.6" has unmet peer dependency "react@^16.14.0".
warning " > @agoric/ui-components@0.2.6" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-26895d38-0381-4927-86bd-80e11d68f0e0 > @agoric/xsnap > @rollup/plugin-node-resolve@6.1.0" has unmet peer dependency "rollup@^1.20.0".
warning "workspace-aggregator-26895d38-0381-4927-86bd-80e11d68f0e0 > @agoric/xsnap > rollup-plugin-terser@5.3.1" has unmet peer dependency "rollup@>=0.66.0 <3".
warning "workspace-aggregator-26895d38-0381-4927-86bd-80e11d68f0e0 > @agoric/ui-components > eslint-config-react-app@6.0.0" has incorrect peer dependency "eslint-plugin-import@^2.22.0".
warning "workspace-aggregator-26895d38-0381-4927-86bd-80e11d68f0e0 > @agoric/ui-components > eslint-config-react-app@6.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^6.3.1".
[5/5] 🔨  Building fresh packages...
[1/4] ⠂ re2
[-/4] ⠂ waiting...
[3/4] ⠂ node-lmdb
error /Users/katesills/code/agoric-sdk/node_modules/re2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/katesills/code/agoric-sdk/node_modules/re2
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@16.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
(node:45630) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/katesills/code/agoric-sdk/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/katesills/code/agoric-sdk/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/katesills/code/agoric-sdk/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/katesills/Library/Caches/node-gyp/16.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/katesills/Library/Caches/node-gyp/16.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/katesills/code/agoric-sdk/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/katesills/Library/Caches/node-gyp/16.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/katesills/code/agoric-sdk/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/re2/lib/addon.o
In file included from ../lib/addon.cc:1:
In file included from ../lib/./wrapped_re2.h:4:
In file included from /Users/katesills/Library/Caches/node-gyp/16.0.0/include/node/node.h:63:
In file included from /Users/katesills/Library/Caches/node-gyp/16.0.0/include/node/v8.h:30:
/Users/katesills/Library/Caches/node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../lib/addon.cc:1:
In file included from ../lib/./wrapped_re2.h:5:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/katesills/Library/Caches/node-gyp/16.0.0/include/node/v8.h:5571:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATED("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/katesills/Library/Caches/node-gyp/16.0.0/include/node/v8config.h:415:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
1 warning and 1 error generated.
make: *** [Release/obj.target/re2/lib/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/katesills/code/agoric-sdk/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/katesills/.nvm/versions/node/v16.0.0/bin/node" "/Users/katesills/code/agoric-sdk/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/katesills/code/agoric-sdk/node_modules/re2
gyp ERR! node -v v16.0.0
```

**Comment by michaelfig** [comment]
Refs: uhop/node-re2#100

**Comment by warner** [comment]
I saw a similar error with node-16.1.0 and `node-lmdb`:
```
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
In file included from /home/warner/.cache/node-gyp/16.1.0/include/node/v8.h:30,
                 from ../src/node-lmdb.h:29,
                 from ../src/node-lmdb.cpp:24:
/home/warner/.cache/node-gyp/16.1.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/home/warner/.cache/node-gyp/16.1.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  452 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
...
```

**Comment by danishyasin33** [comment]
### UPDATE:
- This issue was because I did not install the `build-essential` package fully, which meant I was missing the `make` package. 
- After installing the missing package, the sdk still failed to install on Node 16.9.1. 
- I switched to v14.17.6 and it built successfully. 

### Side note: 
- I am using files across OS systems while using WSL. 

______________________________________________________________________________________________________________________________________
I am facing a similar issue here while trying to install agoric-sdk using `yarn install` on windows wsl. 

tried Node versions: 
- 16.0.0
- 16.9.1


```
error /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-lmdb: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-lmdb
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@16.0.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.0.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.0.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-lmdb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/danishyasin33/.cache/node-gyp/16.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/danishyasin33/.cache/node-gyp/16.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/danishyasin33/.cache/node-gyp/16.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-lmdb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/node_modules/which/which.js:10:17)
gyp ERR! stack     at /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/node_modules/which/which.js:54:21)
gyp ERR! stack     at /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/node_modules/which/which.js:69:33)
gyp ERR! stack     at /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/node_modules/which/which.js:80:22
gyp ERR! stack     at /mnt/g/Development/Agoric/agoric-sdk/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /mnt/g/Development/Agoric/agoric-sdk/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:194:21)
gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
gyp ERR! command "/home/danishyasin33/.nvm/versions/node/v16.0.0/bin/node" "/mnt/g/Development/Agoric/agoric-sdk/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-lmdb
```

**Comment by michaelfig** [comment]
Hi @danishyasin33!

This error is unrelated to Node 16.  Your error is:

> gyp ERR! build error
> gyp ERR! stack Error: not found: make

You will need to `apt-get install build-essential` on Ubuntu (such as WSL) to be able to compile Node.js extensions.  There may be other packages you need to install too.

If that doesn't solve the problem, please open a different issue, and we can discuss it there.
