### ISSUE TITLE
Multipool Autoswap - SwapOut - Secondary to Secondary case violates rights conservation

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3071]
## Describe the bug

When analyzing multipoolAutoswap to ensure that rights were being conserved in all the reallocations, I found that the code in swap.js starting at line 216 was not right. Here's the stagings for the reallocation. The users' seat:

https://github.com/Agoric/agoric-sdk/blob/99a34c6cbd49b076a6965bcda318ae7647a4b106/packages/zoe/src/contracts/multipoolAutoswap/swap.js#L227-L232

The pool for the brandIn:

https://github.com/Agoric/agoric-sdk/blob/99a34c6cbd49b076a6965bcda318ae7647a4b106/packages/zoe/src/contracts/multipoolAutoswap/swap.js#L234-L240

The pool for the brandOut:

https://github.com/Agoric/agoric-sdk/blob/99a34c6cbd49b076a6965bcda318ae7647a4b106/packages/zoe/src/contracts/multipoolAutoswap/swap.js#L242-L251

The amounts in the amountIn brand should be conserved (if we add it to one seat, we must subtract it from another, etc). However, we are adding it to the pool *and* giving it back to the user. That can't be right.

**Comment by dtribble** [comment]
Verified manually. 
```
2021-05-10T20:10:59.690Z SwingSet: kernel: SwingSet:vatWorker ----- VV.6  2 vaultSeat proposal { want: {}, give: {}, exit: { onDemand: null } }
Logging sent error stack (Error#1)
Error#1: The reallocation was not offer safe
Error: The reallocation was not offer safe
 at construct (0:0)
 at Error (0:0)
 at makeError (0:0)
 at fail (0:0)
 at baseAssert (0:0)
 at stage (0:0)
 at swapOut (0:0)
 at (0:0)
 at win (0:0)
 at (0:-91128336)

Error#1 ERROR_NOTE: Thrown from: (Error#2) : 335 . 0
Error#1 ERROR_NOTE: Sent as error:liveSlots:v19#70001
Error#2: Event: 334.1
Error: Event: 334.1
 at construct (0:0)
 at Error (0:0)
 at trackTurns (0:0)
 at handle (0:0)
 at apply (0:0)
 at �y�F` (0:0)
 at addSeat (0:0)
 at (0:0)
 at win (0:0)
 at (0:-91128336)

Error#2 ERROR_NOTE: Caused by: (Error#3)
Error#3: Event: 333.1
Error: Event: 333.1
 at construct (0:0)
 at Error (0:0)
 at trackTurns (0:0)
 at handle (0:0)
 at deliver (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

Error#1 ERROR_NOTE: Sent as error:liveSlots:v19#70002
Logging sent error stack (Error#1)
Error: The reallocation was not offer safe
Logging sent error stack (RemoteError(error:liveSlots:v19#70002)#1)
RemoteError(error:liveSlots:v19#70002)#1: The reallocation was not offer safe
Error: The reallocation was not offer safe
 at construct (0:0)
 at Error (0:0)
 at makeError (0:0)
 at fullRevive (0:0)
 at unserialize (0:0)
 at notifyOnePromise (0:0)
 at notify (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

RemoteError(error:liveSlots:v19#70002)#1 ERROR_NOTE: Rejection from: (Error#2) : 900 . 0
RemoteError(error:liveSlots:v19#70002)#1 ERROR_NOTE: Sent as error:liveSlots:v11#70001
Error#2: Event: 899.1
Error: Event: 899.1
 at construct (0:0)
 at Error (0:0)
 at trackTurns (0:0)
 at handle (0:0)
 at deliver (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

UnhandledPromiseRejectionWarning: (RemoteError(error:liveSlots:v11#70001)#1)
RemoteError(error:liveSlots:v11#70001)#1: The reallocation was not offer safe

  at fullRevive (packages/marshal/src/marshal.js:526:43)
  at meteredConstructor.unserialize (packages/marshal/src/marshal.js:609:19)
  at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:720:19)
  at notify (packages/SwingSet/src/kernel/liveSlots.js:733:7)
  at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:843:11)

RemoteError(error:liveSlots:v11#70001)#1 ERROR_NOTE: Rejection from: (Error#2) : 6731 . 0
Nested error under RemoteError(error:liveSlots:v11#70001)#1
  Error#2: Event: 6729.2
  
    at Function.applyMethod (packages/tame-metering/src/tame.js:202:19)
    at Proxy.eval (packages/eventual-send/src/E.js:37:126)
    at meteredConstructor.acceptOffer (packages/dapp-svelte-wallet/api/src/lib-wallet.js:1029:51)
  
Logging sent error stack (RemoteError(error:liveSlots:v19#70001)#3)
RemoteError(error:liveSlots:v19#70001)#3: The reallocation was not offer safe
Error: The reallocation was not offer safe
 at construct (0:0)
 at Error (0:0)
 at makeError (0:0)
 at fullRevive (0:0)
 at fullRevive (0:0)
 at unserialize (0:0)
 at deliver (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

RemoteError(error:liveSlots:v19#70001)#3 ERROR_NOTE: Rejection from: (Error#4) : 905 . 0
RemoteError(error:liveSlots:v19#70001)#3 ERROR_NOTE: Sent as error:liveSlots:v11#70002
Error#4: Event: 904.1
Error: Event: 904.1
 at construct (0:0)
 at Error (0:0)
 at trackTurns (0:0)
 at handle (0:0)
 at deliver (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

UnhandledPromiseRejectionWarning: (RemoteError(error:liveSlots:v11#70002)#3)
RemoteError(error:liveSlots:v11#70002)#3: The reallocation was not offer safe

  at fullRevive (packages/marshal/src/marshal.js:526:43)
  at meteredConstructor.unserialize (packages/marshal/src/marshal.js:609:19)
  at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:720:19)
  at notify (packages/SwingSet/src/kernel/liveSlots.js:733:7)
  at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:843:11)

RemoteError(error:liveSlots:v11#70002)#3 ERROR_NOTE: Rejection from: (Error#4) : 6792 . 0
Nested error under RemoteError(error:liveSlots:v11#70002)#3
  Error#4: Event: 6791.1
  
    at Function.applyMethod (packages/tame-metering/src/tame.js:202:19)
    at Proxy.eval (packages/eventual-send/src/E.js:37:126)
    at eval (packages/dapp-svelte-wallet/api/src/lib-wallet.js:473:17)
 ```
