### ISSUE TITLE
CapTP Cannot read property 'res' of undefined

### ISSUE THREAD

**Issue by mhofman** [Agoric/agoric-sdk#3289]
## Describe the bug
The load gen seem to sometimes cause a non-fatal error in CapTP when starting. It feels like a race where something is not yet initialized

## To Reproduce
1. Checkout https://github.com/Agoric/testnet-load-generator/ and follow setup instructions for chain and client
2. Run `yarn loadgen`
3. Observe error (or not)

## Expected behavior
No errors

## Platform Environment
 - **what OS are you using? what version of Node.js?** WSL2 (Ubuntu), node 14
 - **is there anything special/unusual about your platform?** 
 - **what version of the Agoric-SDK are you using? (run `git describe --tags --always`)** commit `fa7ff5e55e15e49d366852f5435b6dfa81396f73`

## Additional context
This was observed a few times as part of the automated load gen runner (not yet checked in), which performs the reproduction steps programmatically.

## Stacktrace
<details>

```
TypeError#1: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#2)
TypeError#2: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#3)
TypeError#3: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#4)
TypeError#4: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#5)
TypeError#5: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#6)
TypeError#6: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#7)
TypeError#7: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#8)
TypeError#8: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#9)
TypeError#9: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#10)
TypeError#10: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#11)
TypeError#11: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

**Comment by zarutian** [comment]
hmm... when I tried to figgure out where the other end of the websocket I ended up in twisty code passages and got lost.

pinging @michaelfig as he is the asigned one

**Comment by zarutian** [comment]
self-notes, in Icelandic:
  lítur út fyrir að `agoric start local-solo 8000` byrjar [hér](https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/lib/start.js) og CapTp websocket load-gen notar sé höndlað af þeim ferli. Rangt, sá ferill er í næsta skrefi.
Sem keyrir up Docker mynd sem byrjar að keyra [þennan kóða](https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/lib/entrypoint.js)
Sem er smá skel utan um [main.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/lib/main.js). Eitt af powers sem það fær er makeWebsocket.
main.js notar Command frá nodejs pakkanum Commander til að keyra up ./start.js í sömu möppu.
Pathstrengurinn '../../solo/src/entrypoint.cjs' kemur við sögu. Sem er [þessi skrá](https://github.com/Agoric/agoric-sdk/blob/master/packages/solo/src/entrypoint.cjs).
[Web.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/solo/src/web.js) virðist það sem ég er að leita að.
[Þessi partur](https://github.com/Agoric/agoric-sdk/blob/master/packages/solo/src/web.js#L277-L284) breytir websocket skilaboðum í ákall á inboundCommand með JSON deserialized innihaldi þeirra.
buildCommand kemur frá [þessari skrá](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/devices/command.js)

**Comment by zarutian** [comment]
Oh, look what I [found](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/vats/comms/dispatch.js#L79-L99).

Looking into if the comms vat got confused which phone-handset it uttered which CapTP level messages.

**Comment by michaelfig** [comment]
I'm grasping at straws here.  It may be something deeper underlying, as @zarutian is considering.

@mhofman, have you seen this error keep happening now that you're running more often?  If so, maybe I can meet with you sometime to try to catch it in vitro?

**Comment by zarutian** [comment]
Due to other things I have not dug deep enough to find the origin of the problem.

@michaelfig would it be a good idea to switch the type of questionIds from integers to strings that have integers prefaced with a seperator ('#' or some such) and the vat name? (the thing passed in as first argument to makeCapTPconnection)

I hold forth that change makes debugging this much easier.

**Comment by michaelfig** [comment]
> @michaelfig would it be a good idea to switch the type of questionIds from integers to strings that have integers prefaced with a seperator ('#' or some such) and the vat name? (the thing passed in as first argument to makeCapTPconnection)

Gladly!

**Comment by michaelfig** [comment]
I think I found the answer to this.

The `ag-solo` starts a forked process with a CapTP connection to install the wallet on the chain.  If the `ag-solo` is interrupted, that forked process often continues to run.

This appears to confuse something in the solo when the solo is restarted.

I will look into how this happens, but I intend to prevent this situation by killing off the forked process at the same time as when the `ag-solo` exits.

**Comment by mhofman** [comment]
I need to look into reproducing this again, but I believe I got this to happen without any zombie process.

**Comment by mhofman** [comment]
Killing off forked processes when `ag-solo` quits would be great though.
