### ISSUE TITLE
kernel panic due to bootstrap failure results in obscure diagnostic

### ISSUE THREAD

**Issue by danwt** [Agoric/agoric-sdk#3700]
_Surfaced from @informalsystems audit of Agoric/agoric-sdk/SwingSet at hash 774cb6ad306395e261027a1869cc3ea9db451823_

## The bug

The following sequence results in a kernel panic

1. Resolve a promise to itself in user vat code (correctly triggers error)
2. Await said promise

## To Reproduce

Run the below Vat or similar
```
function createPromiseParts() {

  let res;
  let rej;

  let promise = new Promise((resolve, reject) => {
    res = resolve;
    rej = reject;
  });

  return [promise, res, rej]

}

export function buildRootObject(_vatPowers) {

  return Far('root', {

    async do() {
      let [p, res, rej] = createPromiseParts();
      res(p)
      await (p)
    }

  });
}

```

## Expected behavior

The kernel should not panic

## Output

```
Logging sent error stack (TypeError#1)
TypeError#1: Chaining cycle detected for promise [object Promise]

  at <anonymous>
  at Alleged: root.do (packages/swingset-runner-alt/demo/aaIssueBots/myvat.js:24:7)

TypeError#1 ERROR_NOTE: Rejection from: (Error#2) : 3 . 0
TypeError#1 ERROR_NOTE: Sent as error:liveSlots:v2#70001
Nested error under TypeError#1
  Error#2: Event: 2.1

    at deliver (packages/SwingSet/src/kernel/liveSlots.js:729:28)
    at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1005:11)

Logging sent error stack (RemoteTypeError(error:liveSlots:v2#70001)#3)
RemoteTypeError(error:liveSlots:v2#70001)#3: Chaining cycle detected for promise [object Promise]

  at fullRevive (packages/marshal/src/marshal.js:518:43)
  at Object.unserialize (packages/marshal/src/marshal.js:601:19)
  at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:805:19)
  at notify (packages/SwingSet/src/kernel/liveSlots.js:818:7)
  at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1010:11)

RemoteTypeError(error:liveSlots:v2#70001)#3 ERROR_NOTE: Rejection from: (Error#4) : 2 . 0
RemoteTypeError(error:liveSlots:v2#70001)#3 ERROR_NOTE: Rejection from: (Error#5) : 1 . 1
RemoteTypeError(error:liveSlots:v2#70001)#3 ERROR_NOTE: Sent as error:liveSlots:v1#70001
Nested 2 errors under RemoteTypeError(error:liveSlots:v2#70001)#3
  Error#4: Event: 1.1

    at Proxy.eval (packages/eventual-send/src/E.js:38:49)
    at Alleged: root.bootstrap (packages/swingset-runner-alt/demo/aaIssueBots/bootstrap.js:22:34)
    at runMicrotasks (<anonymous>)

  Error#4 ERROR_NOTE: Caused by: (Error#5)
  Nested error under Error#4
    Error#5: Event: 0.1

      at deliver (packages/SwingSet/src/kernel/liveSlots.js:729:28)
      at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1005:11)
      at runMicrotasks (<anonymous>)

##### KERNEL PANIC: kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v1#70001\",\"message\":\"Chaining cycle detected for promise [object Promise]\",\"name\":\"TypeError\"}","slots":[]} #####
kernel failure in crank 4: Error: kernel panic kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v1#70001\",\"message\":\"Chaining cycle detected for promise [object Promise]\",\"name\":\"TypeError\"}","slots":[]} (Error#6)
Error#6: kernel panic kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v1#70001\",\"message\":\"Chaining cycle detected for promise [object Promise]\",\"name\":\"TypeError\"}","slots":[]}

  at panic (packages/SwingSet/src/kernel/kernel.js:283:26)
  at doResolve (packages/SwingSet/src/kernel/kernel.js:333:9)
  at resolve (packages/SwingSet/src/kernel/kernelSyscall.js:114:5)
  at Object.doKernelSyscall (packages/SwingSet/src/kernel/kernelSyscall.js:155:16)
  at vatSyscallHandler (packages/SwingSet/src/kernel/kernel.js:882:43)
  at syscallFromWorker (packages/SwingSet/src/kernel/vatManager/manager-helper.js:231:18)
  at doSyscall (packages/SwingSet/src/kernel/vatManager/supervisor-helper.js:72:11)
  at Object.resolve (packages/SwingSet/src/kernel/vatManager/supervisor-helper.js:105:31)
  at eval (packages/SwingSet/src/kernel/liveSlots.js:771:15)
```

## Platform Environment
- OS: macOS 11.5
- Node version: v14.17.3
- Agoric SDK version: @agoric/sdk@6.0.0-92-g6302c34ca (necessary to get vats running)

**Comment by dckc** [comment]
wild... how does this relate to the TLA+ model? Is this problem also in the model? Or is it a difference between the model and the implementation?

**Comment by warner** [comment]
I think there are three separate things going on here, and none seem surprising. I'm guessing this is driven by a `bootstrap()` method in the bootstrap vat? Could you post the code you used in the bootstrap vat to drive this? That'd help to confirm my interpretation.

The first is that resolving a Promise to itself is an error, which will be thrown in the `resolve(p)` call. Any function that does this will throw an Error. This is part of the JavaScript specification. Any *async* function which throws any error will cause its result promise to be rejected with that same Error.

The second is that our serialization code is very enthusiastic about printing the details of errors, both on the emitting side (as the target vat serializes the Error during the resolution of the `do()` result promise), and on the receiving side (as the bootstrap vat deserializes the Error to resolve the Promise returned by `E(vats.target).do()`). This is noisy, but harmless.

The third is that, by design, any failure in the `bootstrap()` method causes a kernel panic. In a real application, if the bootstrap method fails, then something very serious has gone wrong, and we don't want to proceed any further.

I think that if you were to replace the `do()` body with a simple `throw Error('foo')`, you'd get a similar kernel panic (but with different error messages). Alternatively, if you changed `bootstrap()` to catch and ignore the error it got back from the eventual `do()`, the kernel would not panic. Something like:

```js
bootstrap(vats) {
  E(vats.target).do().catch(err => console.log('ignoring error'));
}
```

or:
```js
async bootstrap(vats) {
  try {
    await E(vats.target).do();
  } catch(e) {
    console.log('ignoring error');
  }
}
```

instead of:
```js
async bootstrap(vats) {
  await E(vats.target).do();
}
```

**Comment by dckc** [comment]
> ... by design, any failure in the `bootstrap()` method causes a kernel panic.

It would be nice if the KERNEL PANIC message said something like "... bootstrap() failure is fatal". Do you see a straightforward way to tweak that?

**Comment by dckc** [comment]
adding **technical-debt**, which @FUDCo paid some interest on recently

Is the kernel in a position to give a full stack trace?

**Comment by abebeos** [comment]
@dckc , this one still relevant?
