### ISSUE TITLE
`await E(other).nonExistentFun()` in bootstrap triggers kernel panic

### ISSUE THREAD

**Issue by danwt** [Agoric/agoric-sdk#3701]
_Surfaced from @informalsystems audit of Agoric/agoric-sdk/SwingSet at hash 774cb6ad306395e261027a1869cc3ea9db451823_

## The bug

The kernel panics if awaiting a method call on an (eventualized) reference.

## To Reproduce

Run the below Vat or similar
```
export function buildRootObject(_vatPowers) {

  return Far('root', {

    async do(other) {
      await E(other).nonExistentFun()
    }

  });
}
```

and call `do` from another Vat with a Vat reference as argument.

## Expected behavior

The kernel should not panic

## Output

```
Logging sent error stack (TypeError#1)
TypeError#1: target has no method "nonExistentFun", has ["do"]

TypeError#1 ERROR_NOTE: Thrown from: (Error#2) : 5 . 0
TypeError#1 ERROR_NOTE: Sent as error:liveSlots:v3#70001
Nested error under TypeError#1
  Error#2: Event: 4.1

    at deliver (packages/SwingSet/src/kernel/liveSlots.js:729:28)
    at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1005:11)

Logging sent error stack (RemoteTypeError(error:liveSlots:v3#70001)#3)
RemoteTypeError(error:liveSlots:v3#70001)#3: target has no method "nonExistentFun", has ["do"]

  at fullRevive (packages/marshal/src/marshal.js:518:43)
  at Object.unserialize (packages/marshal/src/marshal.js:601:19)
  at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:805:19)
  at notify (packages/SwingSet/src/kernel/liveSlots.js:818:7)
  at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1010:11)

RemoteTypeError(error:liveSlots:v3#70001)#3 ERROR_NOTE: Rejection from: (Error#4) : 4 . 0
RemoteTypeError(error:liveSlots:v3#70001)#3 ERROR_NOTE: Rejection from: (Error#5) : 3 . 1
RemoteTypeError(error:liveSlots:v3#70001)#3 ERROR_NOTE: Sent as error:liveSlots:v2#70001
Nested 2 errors under RemoteTypeError(error:liveSlots:v3#70001)#3
  Error#4: Event: 3.1

    at Proxy.eval (packages/eventual-send/src/E.js:38:49)
    at Alleged: root.do (packages/swingset-runner-alt/demo/aaIssueBots/myvat.js:11:29)

  Error#4 ERROR_NOTE: Caused by: (Error#5)
  Nested error under Error#4
    Error#5: Event: 2.1

      at deliver (packages/SwingSet/src/kernel/liveSlots.js:729:28)
      at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1005:11)

Logging sent error stack (RemoteTypeError(error:liveSlots:v2#70001)#6)
RemoteTypeError(error:liveSlots:v2#70001)#6: target has no method "nonExistentFun", has ["do"]

  at fullRevive (packages/marshal/src/marshal.js:518:43)
  at Object.unserialize (packages/marshal/src/marshal.js:601:19)
  at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:805:19)
  at notify (packages/SwingSet/src/kernel/liveSlots.js:818:7)
  at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1010:11)

RemoteTypeError(error:liveSlots:v2#70001)#6 ERROR_NOTE: Rejection from: (Error#7) : 2 . 0
RemoteTypeError(error:liveSlots:v2#70001)#6 ERROR_NOTE: Rejection from: (Error#8) : 1 . 1
RemoteTypeError(error:liveSlots:v2#70001)#6 ERROR_NOTE: Sent as error:liveSlots:v1#70001
Nested 2 errors under RemoteTypeError(error:liveSlots:v2#70001)#6
  Error#7: Event: 1.1

    at Proxy.eval (packages/eventual-send/src/E.js:38:49)
    at Alleged: root.bootstrap (packages/swingset-runner-alt/demo/aaIssueBots/bootstrap.js:22:34)
    at runMicrotasks (<anonymous>)

  Error#7 ERROR_NOTE: Caused by: (Error#8)
  Nested error under Error#7
    Error#8: Event: 0.1

      at deliver (packages/SwingSet/src/kernel/liveSlots.js:729:28)
      at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:1005:11)
      at runMicrotasks (<anonymous>)

##### KERNEL PANIC: kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v1#70001\",\"message\":\"target has no method \\\"nonExistentFun\\\", has [\\\"do\\\"]\",\"name\":\"TypeError\"}","slots":[]} #####
kernel failure in crank 6: Error: kernel panic kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v1#70001\",\"message\":\"target has no method \\\"nonExistentFun\\\", has [\\\"do\\\"]\",\"name\":\"TypeError\"}","slots":[]} (Error#9)
Error#9: kernel panic kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v1#70001\",\"message\":\"target has no method \\\"nonExistentFun\\\", has [\\\"do\\\"]\",\"name\":\"TypeError\"}","slots":[]}

  at panic (packages/SwingSet/src/kernel/kernel.js:283:26)
  at doResolve (packages/SwingSet/src/kernel/kernel.js:333:9)
  at resolve (packages/SwingSet/src/kernel/kernelSyscall.js:114:5)
  at Object.doKernelSyscall (packages/SwingSet/src/kernel/kernelSyscall.js:155:16)
  at vatSyscallHandler (packages/SwingSet/src/kernel/kernel.js:882:43)
  at syscallFromWorker (packages/SwingSet/src/kernel/vatManager/manager-helper.js:231:18)
  at doSyscall (packages/SwingSet/src/kernel/vatManager/supervisor-helper.js:72:11)
  at Object.resolve (packages/SwingSet/src/kernel/vatManager/supervisor-helper.js:105:31)
  at eval (packages/SwingSet/src/kernel/liveSlots.js:771:15)
```

## Platform Environment
- OS: macOS 11.5
- Node version: v14.17.3
- Agoric SDK version: @agoric/sdk@6.0.0-92-g6302c34ca (necessary to get vats running)

**Comment by warner** [comment]
I think this is the same issue as in https://github.com/Agoric/agoric-sdk/issues/3700#issuecomment-911011797 : if the bootstrap method fails, the kernel panics, as expected. I don't think there's anything special about the non-existent method error: if `do()` fails in any way, then a `bootstrap()` which is `await`ing the result promise will cause a kernel panic (because that means the `bootstrap()` method fails with the same error).

**Comment by dckc** [comment]
as @warner explains, kernel panic on bootstrap failure is as-designed.
