### ISSUE TITLE
Chain export error: `keeper.LienAccount` is not `types.GenesisAccount`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#3933]
## To Reproduce
1. Go to `packages/cosmic-swingset`
2. Run `make scenario2-setup scenario2-run-chain`
3. Wait for some blocks to be produced (get the `block NN commit` messages)
4. Control-C
5. Export the chain data, and you get a crash:

```console
$ ag-chain-cosmos --home=t1/n0 export
panic: interface conversion: keeper.LienAccount is not types.GenesisAccount: missing method Validate

goroutine 13 [running]:
github.com/cosmos/cosmos-sdk/x/auth.ExportGenesis.func1(0x11a697120, 0xc0012401c0, 0x11a697120)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/x/auth/genesis.go:36 +0x4e
github.com/Agoric/agoric-sdk/golang/cosmos/x/lien/types.(*WrappedAccountKeeper).IterateAccounts.func1(0x11a6969a0, 0xc001246a80, 0x11a6967a0)
        /Users/michael/agoric/agoric-sdk/golang/cosmos/x/lien/types/accountkeeper.go:64 +0x63
github.com/cosmos/cosmos-sdk/x/auth/keeper.accountKeeper.IterateAccounts(0x11a65cb40, 0xc000e22610, 0x11a6967a0, 0xc000e22570, 0x11a6967a0, 0xc000e22570, 0xc0004fa120, 0x11a65cb40, 0xc000e22710, 0x11a65cbc0, ...)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/x/auth/keeper/account.go:80 +0x1f6
github.com/Agoric/agoric-sdk/golang/cosmos/x/lien/types.(*WrappedAccountKeeper).IterateAccounts(0xc0000f7740, 0x11a67fa80, 0xc000042088, 0x11a699420, 0xc0004f3f40, 0x0, 0x0, 0x0, 0x0, 0x2d, ...)
        /Users/michael/agoric/agoric-sdk/golang/cosmos/x/lien/types/accountkeeper.go:63 +0xbe
github.com/cosmos/cosmos-sdk/x/auth.ExportGenesis(0x11a67fa80, 0xc000042088, 0x11a699420, 0xc0004f3f40, 0x0, 0x0, 0x0, 0x0, 0x2d, 0x0, ...)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/x/auth/genesis.go:35 +0x15d
github.com/cosmos/cosmos-sdk/x/auth.AppModule.ExportGenesis(0x11a6a1560, 0xc0000f7740, 0x0, 0x11a67fa80, 0xc000042088, 0x11a699420, 0xc0004f3f40, 0x0, 0x0, 0x0, ...)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/x/auth/module.go:151 +0x85
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesis(0xc000d150a0, 0x11a67fa80, 0xc000042088, 0x11a699420, 0xc0004f3f40, 0x0, 0x0, 0x0, 0x0, 0x2d, ...)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/types/module/module.go:327 +0x135
github.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).ExportAppStateAndValidators(0xc0000e6d00, 0xc001289500, 0x11b39bd18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/michael/agoric/agoric-sdk/golang/cosmos/app/export.go:32 +0x1e8
github.com/Agoric/agoric-sdk/golang/cosmos/daemon/cmd.createSimappAndExport(0x11a680940, 0xc001289500, 0x11a6987a0, 0xc0004fa118, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x11b39bd18, 0x0, ...)
        /Users/michael/agoric/agoric-sdk/golang/cosmos/daemon/cmd/root.go:261 +0x2cd
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc000dc1400, 0xc0011eef90, 0x0, 0x1, 0x0, 0x0)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/server/export.go:71 +0x434
github.com/spf13/cobra.(*Command).execute(0xc000dc1400, 0xc0011eef80, 0x1, 0x1, 0xc000dc1400, 0xc0011eef80)
        /Users/michael/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000da4000, 0x0, 0x0, 0xc00114cd60)
        /Users/michael/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/michael/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/michael/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000da4000, 0xc00114cd60, 0x1f, 0xc00051d200, 0x11a69c980)
        /Users/michael/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.44.0-alpha.agoric.5/server/cmd/execute.go:36 +0x285
github.com/Agoric/agoric-sdk/golang/cosmos/daemon.RunWithController(0xc0011533e0)
        /Users/michael/agoric/agoric-sdk/golang/cosmos/daemon/main.go:74 +0x14b
main.RunAgCosmosDaemon.func2(0xc0011533e0)
        /Users/michael/agoric/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:67 +0x2b
created by main.RunAgCosmosDaemon
        /Users/michael/agoric/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:64 +0x137
$
```

## Expected behavior
Instead of a crash, the export produces a bunch of JSON data for a new `genesis.json` file.

## Platform Environment
 - what OS are you using? MacOS 11.6 what version of Node.js? v14.17.6
 - is there anything special/unusual about your platform? not really
 - what version of the Agoric-SDK are you using? agoricdev-4-71-g975974eb2

## Additional context
n/a

## Screenshots
n/a

**Comment by michaelfig** [comment]
The following patch adds a (currently failing) test for this issue to `cd packages/cosmic-swingset && yarn test`:

```diff
diff --git a/packages/cosmic-swingset/test/test-make.js b/packages/cosmic-swingset/test/test-make.js
index 23d786b31..a7e456bee 100644
--- a/packages/cosmic-swingset/test/test-make.js
+++ b/packages/cosmic-swingset/test/test-make.js
@@ -33,4 +33,13 @@ test('make and exec', async t => {
       resolve();
     }),
   );
+  await new Promise(resolve =>
+    spawn('bin/ag-chain-cosmos', ['export', '--home=t1/n0'], {
+      cwd: `${dirname}/..`,
+      stdio: ['ignore', 'ignore', 'inherit'],
+    }).addListener('exit', code => {
+      t.is(code, 0, 'export exits successfully');
+      resolve();
+    }),
+  );
 });
```
