### ISSUE TITLE
false match on lines ending with `import`

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#43]
The SES code that prohibits dynamic import expressions doesn't use a full parser, so it gets false matches when the word `import` appears just before a comment opening token, possibly separated by whitespace. Twice I've had this trigger on comments in my code that look like:

```
stuff()
// this is an import
// of something
morestuff()
```

The scanner doesn't know that `import` is already in a comment, so it is guarding against:

```
stuff();
import
// sneaky comment
('dynamic module to import');
```

SES should eventually learn to ignore the first, but for now it would be nice if SwingSet just had a nicer error message. The one you get happens after `rollup` finishes combining all the files into a single string, and then you get an error referring to the line number in the merged file:

```
(node:21506) UnhandledPromiseRejectionWarning: SyntaxError: possible import expression rejected around line 2475
    at rejectImportExpressions (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1050:11)
    at rejectDangerousSources (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1087:3)
    at Object.rewrite (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1094:5)
    at allTransforms.reduce.src.src (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1205:61)
    at Array.reduce (<anonymous>)
    at eval (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1204:45)
    at /home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1271:46
    at realmEvaluate (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:1504:10)
    at callAndWrapError (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:82:14)
    at Realm.evaluate (/home/warner/bindmounts/trees/SwingSet/node_modules/ses/dist/ses.cjs.js:162:14)
(node:21506) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21506) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm thinking maybe we scan the `rollup` output for `/\bimport\s*$/` and then if eval() throws, we print the full line that matched, rather than just the line number of a string that only ever existed in memory. Not sure quite where we'd do this, it may have to go into SES itself.

**Comment by erights** [comment]
@warner I'm assigning to myself and closing, under the assumption that this is fixed enough and is not currently an active thorn in our side. If I need to do more on this, please reopen and leave assigned to me.

**Comment by softmarshmallow** [comment]
Not so related, but i'm having this `Error: SyntaxError: possible import expression rejected around line` error also, cannot find any other reference related to this error message but here. can you share us some context and what caused and how solved the problem?
