### ISSUE TITLE
agoric cli does not work outside of the agoric-sdk repo

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#570]
I'm on Ubuntu

I started with 
```sh
git clone https://github.com/Agoric/agoric-sdk
cd agoric-sdk
yarn install
yarn build
yarn link-cli /usr/local/bin/agoric
```
then
```sh
cd /tmp
agoric init demo
cd demo
agoric install
agoric start
```

All went well except the last command which output was:
```sh
initializing dev
/home/david/projects/agoric-sdk/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake
morgan deprecated default format: use combined format ../../../home/david/projects/agoric-sdk/node_modules/esm/esm.js:1:278827
solo [ 'init', 'dev', '--egresses=fake' ]
fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
error running ag-solo: Error: Command failed: git describe --always --dirty
fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at initBasedir (/home/david/projects/agoric-sdk/packages/cosmic-swingset/lib/ag-solo/init-basedir.js:62:20)
    at solo (/home/david/projects/agoric-sdk/packages/cosmic-swingset/lib/ag-solo/main.js:67:5)
    at Object.<anonymous> (/home/david/projects/agoric-sdk/packages/cosmic-swingset/bin/ag-solo:7:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 6e 69 20 63 65 63 69 20 6e 69 20 61 75 63 75 6e 20 64 65 20 73 65 73 20 72 c3 a9 70 65 72 74 6f 69 72 65 73 20 70 61 72 65 6e 74 ... 31 more bytes>
  ],
  pid: 16499,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 6e 69 20 63 65 63 69 20 6e 69 20 61 75 63 75 6e 20 64 65 20 73 65 73 20 72 c3 a9 70 65 72 74 6f 69 72 65 73 20 70 61 72 65 6e 74 ... 31 more bytes>
}
Maybe the chain has bumped and you need to rerun ag-setup-solo?
setting fake chain with 5 second delay
/home/david/projects/agoric-sdk/packages/cosmic-swingset/bin/ag-solo set-fake-chain --role=two_chain --delay=5 myFakeGCI
morgan deprecated default format: use combined format ../../../../home/david/projects/agoric-sdk/node_modules/esm/esm.js:1:278827
solo [ 'set-fake-chain', '--role=two_chain', '--delay=5', 'myFakeGCI' ]
error running ag-solo: /tmp/demo/.agservers/dev doesn't appear to be an ag-solo base directory
Maybe the chain has bumped and you need to rerun ag-setup-solo?
linking html directories
/home/david/projects/agoric-sdk/packages/cosmic-swingset/bin/ag-solo start --role=two_client
morgan deprecated default format: use combined format ../../../../home/david/projects/agoric-sdk/node_modules/esm/esm.js:1:278827
solo [ 'start', '--role=two_client' ]
error running ag-solo: /tmp/demo/.agservers/dev doesn't appear to be an ag-solo base directory
Maybe the chain has bumped and you need to rerun ag-setup-solo?
```

I do not have this problem when if i stay on the agoric-sdk directory

**Comment by DavidBruant** [comment]
This is probably a duplicate of #562
