### ISSUE TITLE
Incorrect order of arguments in `ag-chain-cosmos`

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#599]
## Reproduction
When launching the "larger demo" as described in the README.md:
```
    cd packages/cosmic-swingset
    make scenario2-setup
    make scenario2-run-chain (in one shell)
    make scenario2-run-client (in a second shell)
```

This recurring message is displayed in terminal:
```
toSwingSet threw error: TypeError: mailboxStorage.has is not a function
    at launch (agoric-sdk/packages/cosmic-swingset/lib/launch-chain.js:55:20)
    at launchAndInitializeDeliverInbound (agoric-sdk/packages/cosmic-swingset/lib/ag-chain-cosmos:128:19)
    at toSwingSet0 (agoric-sdk/packages/cosmic-swingset/lib/ag-chain-cosmos:150:37)
    at toSwingSet (agoric-sdk/packages/cosmic-swingset/lib/ag-chain-cosmos:82:10)
    at Object.fromGo (agoric-sdk/packages/cosmic-swingset/lib/ag-chain-cosmos:59:29)
    at Object.topLevelDomainCallback (domain.js:137:15)
```

## Analysis
The order of the two first parameters of `launch()` is not consistent between the declaration and the usage:

### Declaration
```js
export async function launch(kernelStateDBDir, mailboxStorage, vatsDir, argv) {
```
https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/lib/launch-chain.js#L50

### Usage 1
```js
  const s = await launch(stateDBdir, mailboxStorage, vatsdir, argv);
```
https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/lib/ag-solo/fake-chain.js#L38

### Usage 2
```js
  const s = await launch(mailboxStorage, stateFile, vatsdir, argv);
```
https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/lib/ag-chain-cosmos#L128

**Comment by FUDCo** [comment]
This looks straightforwardly wrong.  It may even be the result of something that got missed when I was refactoring the swing store.  I'll have a fix shortly.
