### ISSUE TITLE
agoric-cli: TypeError <Object <Object <[Object: null prototype] {}>>>: hp.resolve is not a function

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#634]
Following the steps described in the "Getting Started with the Agoric CLI":

```
agoric init demo
cd demo
agoric install
agoric start
```
https://agoric.com/documentation/getting-started/#quick-overview

Leads to this error:
```
error running ag-solo: TypeError <Object <Object <[Object: null prototype] {}>>>: hp.resolve is not a function
    at passStyleOf (demo/.agservers/solo/vats/vat-mints.js:817:18)
    at mustBeSameStructureInternal (demo/.agservers/solo/vats/vat-mints.js:1454:23)
    at mustBeSameStructure (demo/.agservers/solo/vats/vat-mints.js:1531:5)
    at mustBeComparable (demo/.agservers/solo/vats/vat-mints.js:1538:5)
    at makeUnitOps (demo/.agservers/solo/vats/vat-mints.js:1838:5)
    at makeMint (demo/.agservers/solo/vats/vat-mints.js:2167:21)
    at build (demo/.agservers/solo/vats/vat-mints.js:2258:38)
    at eval (demo/.agservers/solo/vats/vat-mints.js:2275:55)
    at build (eval at <anonymous> (eval at createScopedEvaluatorFactory (demo/.agservers/node_modules/ses/dist/ses.cjs.js:1323:10)), <anonymous>:1553:24)
    at Object.makeLiveSlots (eval at <anonymous> (eval at createScopedEvaluatorFactory (demo/.agservers/node_modules/ses/dist/ses.cjs.js:1323:10)), <anonymous>:1574:9)
Maybe the chain has bumped and you need to rerun ag-setup-solo?
```

**Comment by michaelfig** [comment]
It works for me.  Make sure you don't have the old `agoric` package installed globally before you follow the steps.

**Comment by jfparadis** [comment]
I don't think that's it:
1. I'm using `npx`
2. I don't have an `agoric` package installed globally:

![Screen Shot 2020-02-28 at 5 19 59 PM](https://user-images.githubusercontent.com/2583204/75598162-96ab9e80-5a4e-11ea-9a7f-5603bf368f8b.png)

Strange. Maybe you have an old version?

**Comment by jfparadis** [comment]
Just tested with a brand new user:

![Screen Shot 2020-02-28 at 5 31 26 PM](https://user-images.githubusercontent.com/2583204/75598440-83013780-5a50-11ea-98ad-f9d3b7466355.png)

**Comment by jfparadis** [comment]
If I install locally instead of using `npx`, it still fails with a different error:

![Screen Shot 2020-02-28 at 5 54 12 PM](https://user-images.githubusercontent.com/2583204/75598835-b85b5480-5a53-11ea-9704-bdce83666770.png)

**Comment by michaelfig** [comment]
It looks to me like somehow the `eventual-send` package was not built.

Can you try:

```sh
cd /Users/test/Documents/agoric-sdk
yarn build
```

and if that doesn't work (solve the `Cannot find module '@agoric/eventual-send'` problem), please post the results of:

```sh
ls -ld /Users/test/Documents/agoric-sdk/node_modules/@agoric/eventual-send
ls -l /Users/test/Documents/agoric-sdk/node_modules/@agoric/eventual-send/dist
```

The first should show that path is a symlink to `../../packages/eventual-send`.  The second should show a set of built files.

I hope this helps!

**Comment by katelynsills** [comment]
@michaelfig do you think we can close this?

**Comment by michaelfig** [comment]
Yup!
