### ISSUE TITLE
Error in replaying transcript trying to revive comms vat.

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#64]
```
doProcess: Replay failed: [deliver, o+10, receive, {"body":"[\"deliver:ro+21:wake:;[1571878446]\"]","slots":[]}]: TypeError: Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at Object.replacer (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-workspace/SES/dist/ses.cjs.js:1308:10)), <anonymous>:1938:39)
    at JSON.stringify (<anonymous>)
    at Object.stringify (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-workspace/SES/dist/ses.cjs.js:1308:10)), <anonymous>:1952:17)
    at replay (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-workspace/SES/dist/ses.cjs.js:1308:10)), <anonymous>:2220:17)
    at Object.send (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-workspace/SES/dist/ses.cjs.js:1308:10)), <anonymous>:2233:27)
    at deliverFromRemote (/Users/chrishibbert/cosmic-workspace/SwingSet/src/vats/comms/index.js:780:15)
    at Object.deliver (/Users/chrishibbert/cosmic-workspace/SwingSet/src/vats/comms/index.js:996:16)
    at process (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-workspace/SES/dist/ses.cjs.js:1308:10)), <anonymous>:2286:48)
```

**Comment by warner** [comment]
It's unlikely we'll be able to reconstruct this.. let's wait until something similiar happens again.
