### ISSUE TITLE
SwingSet reflects cascade back to sender before the resolution of the target

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#67]
This happens in a test of Scenario 2 with AutoSwap and Wallet UIs running in separate clients.

When the AutoSwap UI sends `autoswapGetPrice`, the exchange vat calls

```
    const instanceHandleP = E(registrar).get(instanceId);
    const regAssay0P = E(registrar).get(assayId0);
    const regAssay1P = E(registrar).get(assayId1);
    const unit0P = E(regAssay0P).makeUnits(extent0);
```
The messages are sent off to the chain. 

```
new outbound message 28 ...: deliver:ro+26:get:rp-52;["zoe:autoswap_5496"]
new outbound message 29 ...: deliver:ro+26:get:rp-53;["moola_9794"]
new outbound message 30 ...: deliver:ro+26:get:rp-54;["simolean_5496"]
new outbound message 31 ...: deliver:rp-53:makeUnits:rp-55;[7]
```
When the responses are returned, they come back in a surprising order, and seem to be claiming that the Assay that was requested is already known. Then an error is thrown.

```
deliverInboundToMbx [ [ 29, 'deliver:ro+20:makeUnits:rp+55;[7]' ],
  [ 30, 'resolve:data:rp+52;{"@qclass":"undefined"}' ],
  [ 31, 'resolve:object:rp+53:ro+20;' ],
  [ 32, 'resolve:object:rp+54:ro+21;' ] ] 31
deliverInboundMbx calling Kernel 
doProcess: vat[v13][o+10].receive dispatch failed: Error: rp+55 <<[Object: null prototype] {}> {}> [Error]: rp+55
    at insist (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:22:13)
    at mapInboundResult (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:582:5)
    at deliverFromRemote (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:777:13)
    at Object.deliver (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:996:16)
    at process (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-swingset-top/node_modules/ses/dist/ses.cjs.js:1308:10)), <anonymous>:2198:48)
```

A longer transcript is below the replication instructions here, and I'll retain the full transcript for a while.

commit 0d8a80d85853f946bb151aa835cfd4dc15faac4c, tagged: CommsBugHackathon captures the state of the code. 

You need 6 shells to replicate this. along with copies of cosmic-swingset, wallet-frontend` and `autoswap-frontend`.

Shell 1
``` bash
NUM_SOLOS=2  make scenario2-setup 
make scenario2-run-chain  2>&1 | tee ~/BUGs/S2-Chain-9.log
```

In separate shells, each of the following, in the same cosmic-swingset directory:
```
make scenario2-run-client 
BASE_PORT=8001    make scenario2-run-client
(cd t1/8001; node ../../bin/ag-solo bundle -e init-autoswap zoe:autoswap=../../node_modules/@agoric/ertp/core/zoe/contracts/autoswap.js)
```

run `npm run start` in `wallet-frontend` and `autoswap-frontend`

wallet-frontend has a `.env.local` containing

```
REACT_APP_API_URL="http://localhost:8000"
```
while autoswap-frontend's env.local has 

```
REACT_APP_CONTRACT_ID="zoe:autoswap_5496"
REACT_APP_DAPP_API_URL="http://localhost:8001"
REACT_APP_WALLET_BRIDGE_URL="http://localhost:8000"
```

Start the wallet first, so that when autoswap starts, it'll ask if it should use 8001, since 8000 is in use.

Here's the relevant part of the output of the Dapp's solo vat transcript. For context, I also include the processing of `walletGetPurse`, which was handled correctly.

```
deliverInboundToMbx [] 27
deliverInboundMbx ELSE 
127.0.0.1:50402[2]: new ws connection /
vat-http.inbound (from browser) 24 <[Object: null prototype] {}> { type: 'walletGetPurses' }
  INBOUND  Looping  2
  INBOUND  calling processInbound  1  
  INBOUND  result: false
  INBOUND    No Luck false!!!
  INBOUND  calling processInbound  0  
  INBOUND  result: [object Object]
  INBOUND    Success: [object Object]!!!
  INBOUND    SendResponse([object Object]
deliver { '585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931': { outbox: [], inboundAck: 28 } }
 0 new messages
HTTP: POST /vat 200 269 - 67.363 ms
new block on 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir

 helper said: {"value":"\"{\\\"ack\\\":27,\\\"outbox\\\":[]}\""}

deliverInboundToMbx [] 27
deliverInboundMbx ELSE 
new block on 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir

 helper said: {"value":"\"{\\\"ack\\\":27,\\\"outbox\\\":[]}\""}

deliverInboundToMbx [] 27
deliverInboundMbx ELSE 
new block on 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir

 helper said: {"value":"\"{\\\"ack\\\":27,\\\"outbox\\\":[]}\""}

deliverInboundToMbx [] 27
deliverInboundMbx ELSE 
new block on 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir

 helper said: {"value":"\"{\\\"ack\\\":27,\\\"outbox\\\":[]}\""}

deliverInboundToMbx [] 27
deliverInboundMbx ELSE 
vat-http.inbound (from browser) 25 <[Object: null prototype] {}> {
  type: 'autoswapGetPrice',
  data:
   <[Object: null prototype] {}> {
     instanceId: 'zoe:autoswap_5496',
     extent0: 7,
     assayId0: 'moola_9794',
     assayId1: 'simolean_5496' } }
  INBOUND  Looping  2
  INBOUND  calling processInbound  1  
deliver { '585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931':
   { outbox: [ [Array], [Array], [Array], [Array] ],
     inboundAck: 28 } }
new outbound message 28 for 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931: deliver:ro+26:get:rp-52;["zoe:autoswap_5496"]
new outbound message 29 for 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931: deliver:ro+26:get:rp-53;["moola_9794"]
new outbound message 30 for 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931: deliver:ro+26:get:rp-54;["simolean_5496"]
new outbound message 31 for 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931: deliver:rp-53:makeUnits:rp-55;[7]
 4 new messages
 invoking deliverator
delivering to chain 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931 [ [ 28, 'deliver:ro+26:get:rp-52;["zoe:autoswap_5496"]' ],
  [ 29, 'deliver:ro+26:get:rp-53;["moola_9794"]' ],
  [ 30, 'deliver:ro+26:get:rp-54;["simolean_5496"]' ],
  [ 31, 'deliver:rp-53:makeUnits:rp-55;[7]' ] ] 28
ag-cosmos-helper tx swingset deliver cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp @/var/folders/w4/fz2zg85d71d1m23b8jc00jrw0000gn/T/ag-solo-cosmos-deliver.2019102-68878-utiz1p.f9gud --from ag-solo -ojson --broadcast-mode block --yes --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir
new block on 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir

 helper said: {"height":"73","txhash":"F8688F0BC87F064194DB159B94075D03455A6FFA5E4405956E31290757658554","raw_log":"[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"deliver\"}]}]}]","logs":[{"msg_index":0,"success":true,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"deliver"}]}]}],"gas_wanted":"200000","gas_used":"6904","events":[{"type":"message","attributes":[{"key":"action","value":"deliver"}]}]}


 helper said: {"value":"\"{\\\"ack\\\":31,\\\"outbox\\\":[[29,\\\"deliver:ro+20:makeUnits:rp+55;[7]\\\"],[30,\\\"resolve:data:rp+52;{\\\\\\\"@qclass\\\\\\\":\\\\\\\"undefined\\\\\\\"}\\\"],[31,\\\"resolve:object:rp+53:ro+20;\\\"],[32,\\\"resolve:object:rp+54:ro+21;\\\"]]}\""}

deliverInboundToMbx [ [ 29, 'deliver:ro+20:makeUnits:rp+55;[7]' ],
  [ 30, 'resolve:data:rp+52;{"@qclass":"undefined"}' ],
  [ 31, 'resolve:object:rp+53:ro+20;' ],
  [ 32, 'resolve:object:rp+54:ro+21;' ] ] 31
deliverInboundMbx calling Kernel 
doProcess: vat[v13][o+10].receive dispatch failed: Error: rp+55 <<[Object: null prototype] {}> {}> [Error]: rp+55
    at insist (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:22:13)
    at mapInboundResult (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:582:5)
    at deliverFromRemote (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:777:13)
    at Object.deliver (/Users/chrishibbert/cosmic-swingset-top/node_modules/@agoric/swingset-vat/src/vats/comms/index.js:996:16)
    at process (eval at <anonymous> (eval at createScopedEvaluatorFactory (/Users/chrishibbert/cosmic-swingset-top/node_modules/ses/dist/ses.cjs.js:1308:10)), <anonymous>:2198:48)
deliver { '585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931': { outbox: [], inboundAck: 32 } }
 0 new messages
 invoking deliverator
delivering to chain 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931 [] 32
ag-cosmos-helper tx swingset deliver cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp @/var/folders/w4/fz2zg85d71d1m23b8jc00jrw0000gn/T/ag-solo-cosmos-deliver.2019102-68878-do212p.fz6k --from ag-solo -ojson --broadcast-mode block --yes --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir
new block on 585d3edc26612c152cbe9afd910625cd83cf3d200d2abbad4f75bb126de09931, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1ch5vcmymz35sqhl7tj0wuesfh2d2lehppmkadp --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /Users/chrishibbert/cosmic-swingset-top/t1/8001/ag-cosmos-helper-statedir

 helper said: {"height":"74","txhash":"5652F6963C5A07AAB94DD514399CCFDE3211C3DB16CCDEA892CA2325FA4A4BD7","raw_log":"[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"deliver\"}]}]}]","logs":[{"msg_index":0,"success":true,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"deliver"}]}]}],"gas_wanted":"200000","gas_used":"6904","events":[{"type":"message","attributes":[{"key":"action","value":"deliver"}]}]}
```

**Comment by warner** [comment]
@Chris-Hibbert Does this still happen?

**Comment by Chris-Hibbert** [comment]
The code that used to provoke this issue is now completely different. 

If the issue wasn't observed in other contexts, then it's likely that a subtle coincidence was required to cause it, and it'll no longer happen in this situation. 

Probably best to close it.
