### ISSUE TITLE
SwingSet Kernel Panic: error during tryProcessMessage: ExitCode: v7:zoe exited: property (key) name space exhausted

### ISSUE THREAD

**Issue by ivanlei** [Agoric/agoric-sdk#6911]
## Describe the bug
Jacques Vella Critien from simply vc reports:
 
The testnet halted and is currently down with the following error and it does not seem like it is recoverable. Do you have any suggestions please?
```
SwingSet: kernel: error in kernel.deliver: (ExitCode#1)
ExitCode#1: v7:zoe exited: property (key) name space exhausted
  at new ErrorCode (packages/xsnap/api.js:51:5)
  at ChildProcess.<anonymous> (packages/xsnap/src/xsnap.js:133:22)
  at Object.onceWrapper (node:events:628:26)
  at ChildProcess.emit (node:events:513:28)
SwingSet: kernel: ##### KERNEL PANIC: error during tryProcessMessage: ExitCode: v7:zoe exited: property (key) name space exhausted #####
END_BLOCK error: (ExitCode#1)
portHandler threw (ExitCode#1)
ERR CONSENSUS FAILURE!!! err="ExitCode: v7:zoe exited: property (key) name space exhausted" module=consensus stack="goroutine 49 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go..
```
We can restart the testnet from scratch but how can we avoid this in the future?

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by dckc** [comment]
`ExitCode#1: v7:zoe exited: property (key) name space exhausted` means that the zoe vat ran into a limitation on the number of property names in an XS VM:

https://github.com/Agoric/agoric-sdk/blob/229b935ddc8ab27676b2bb7ee68e3a5408ced557/packages/xsnap/api.js#L29
