### ISSUE TITLE
Issues reviving zoe-sketchbook 

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#716]
I'm working on reviving zoe-sketchbook.

When  I started, Yarn said that packages were out of date. It (I) wanted ERTP 0.4.1. Yarn said that that depends on @agoric/assert@^0.0.1, which wasn't available on the npm registry. 

@michaelfig  published `@agoric/assert@0.0.1`, which fixed this issue, but revealed the next one:

```
yarn test
yarn run v1.21.1
$ tape -r esm 'test/**/*.test.js' | tap-spec
/Users/chrishibbert/zoe-sketchbook/node_modules/@agoric/ertp/src/issuer.js:1
TypeError: E.unwrap is not a function
    at Object.deposit (/Users/chrishibbert/zoe-sketchbook/node_modules/@agoric/ertp/src/issuer.js:44:30)
    at Object.<anonymous> (/Users/chrishibbert/zoe-sketchbook/examples/baytownBucks.js:25:7)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/chrishibbert/zoe-sketchbook/test/baytownBucks.test.js:1)
    at Generator.next (<anonymous>)

error Command failed with exit code 1.
```

The eventual-send that zoe-sketchbook gets via yarn doesn't have `unwrap`. Only the `index.d.ts` was installed under `node-modules/@agoric/eventual-send`. The `index.js` file was MIA.

@michaelfig  published @agoric/eventual-send v0.5.1. After removing node_modules and runninng `yarn install` again, I continue to see `E.unwrap is not a function.`. It's being called from `zoe-sketchbook/node_modules/@agoric/ertp/src/issuer.js:44:30)`

**Comment by michaelfig** [comment]
What's in `zoe-sketchbook/node_modules/@agoric/ertp/node_modules`?  Also try a `grep eventual-send yarn.lock`.  We may need to update the ERTP release, as its old dependency on `@agoric/eventual-send@0.5.0` may be breaking things.

**Comment by Chris-Hibbert** [comment]
```
> ll node_modules/@agoric/ertp/node_modules/
total 0
drwxr-xr-x   4 chrishibbert  128 Mar 17 15:51 @agoric/
drwxr-xr-x  11 chrishibbert  352 Mar 17 15:51 realms-shim/
drwxr-xr-x   6 chrishibbert  192 Mar 17 15:51 ses/
```

```
> grep eventual-send yarn.lock
"@agoric/acorn-eventual-send@^2.0.0":
  resolved "https://registry.yarnpkg.com/@agoric/acorn-eventual-send/-/acorn-eventual-send-2.0.0.tgz#e994d795382c48f7a3fd6f9a6b6365ded68602e2"
    "@agoric/acorn-eventual-send" "^2.0.0"
    "@agoric/eventual-send" "^0.4.4"
    "@agoric/transform-eventual-send" "^1.0.3"
    "@agoric/transform-eventual-send" "^1.1.0"
    "@agoric/eventual-send" "^0.4.5"
    "@agoric/eventual-send" "^0.5.0"
"@agoric/eventual-send@0.5.1":
  resolved "https://registry.yarnpkg.com/@agoric/eventual-send/-/eventual-send-0.5.1.tgz#3406a65cf5c52fa0e047b4f522a5a5d4c99a6fd3"
"@agoric/eventual-send@^0.4.4", "@agoric/eventual-send@^0.4.5":
  resolved "https://registry.yarnpkg.com/@agoric/eventual-send/-/eventual-send-0.4.5.tgz#73d4238b856eef6086b45e3bcf219aeb9e516056"
"@agoric/eventual-send@^0.5.0":
  resolved "https://registry.yarnpkg.com/@agoric/eventual-send/-/eventual-send-0.5.0.tgz#3f5ff42610d079e4257b0f9ffe212d7b3f9d223a"
    "@agoric/eventual-send" "^0.5.0"
"@agoric/transform-eventual-send@^1.0.3":
  resolved "https://registry.yarnpkg.com/@agoric/transform-eventual-send/-/transform-eventual-send-1.0.3.tgz#0dfdeea1450120ebf91c6272b715dc77080d4876"
"@agoric/transform-eventual-send@^1.1.0":
  resolved "https://registry.yarnpkg.com/@agoric/transform-eventual-send/-/transform-eventual-send-1.1.0.tgz#d82d4f64325e951ca07e01bc942bce1889a34aec"
    "@agoric/eventual-send" "^0.5.0"
```

**Comment by michaelfig** [comment]
Yeah, we will probably have to create a new ERTP release to fix this.

**Comment by katelynsills** [comment]
Can we close this now?
