### ISSUE TITLE
Issues when deploying UI in Getting Started

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#727]
I'm working with @tyg on unblocking the Getting Started tutorial. We're now past the point of starting the chain side. When we attempt to deploy the UI side with `agoric deploy ./contract/deploy.js  ./api/deploy.js`, the command doesn't return control, and the chain side shows this error message: 

```
We're currently already running at Error <Object <[Object: null prototype] {}> {}>: here
    at processQueueMessage (/SwingSet-kernel/packages/SwingSet/src/kernel/kernel.js:452:31)
    at Object.run (/SwingSet-kernel/packages/SwingSet/src/kernel/kernel.js:845:15)
error fake processing Error <Object <[Object: null prototype] {}> {}>: Kernel reentrancy is forbidden
    at processQueueMessage (/SwingSet-kernel/packages/SwingSet/src/kernel/kernel.js:448:15)
    at Object.run (/SwingSet-kernel/packages/SwingSet/src/kernel/kernel.js:845:15)
    at Object.run (/Users/chrishibbert/agoric-sdk/packages/SwingSet/src/controller.js:338:21)
    at deliverInbound (/Users/chrishibbert/agoric-sdk/packages/cosmic-swingset/lib/launch-chain.js:106:22)
    at kernelPerformAction (/Users/chrishibbert/agoric-sdk/packages/cosmic-swingset/lib/block-manager.js:27:13)
    at blockManager (/Users/chrishibbert/agoric-sdk/packages/cosmic-swingset/lib/block-manager.js:91:13)
    at simulateBlock (/Users/chrishibbert/agoric-sdk/packages/cosmic-swingset/lib/ag-solo/fake-chain.js:65:15)
    at async Object.deliver [as deliverator] (/Users/chrishibbert/agoric-sdk/packages/cosmic-swingset/lib/ag-solo/fake-chain.js:103:7)
wrote SwingSet checkpoint (mailbox=84), [run=59ms, mb=0ms, save=11ms]
 invoking deliverator; 0 new messages for myFakeGCI
wrote SwingSet checkpoint (mailbox=50), [run=2ms, mb=0ms, save=11ms]
```

**Comment by michaelfig** [comment]
Please try again from scratch (`git pull` the `agoric-sdk`, and rerun `agoric init ...`).  The simple-exchange UI is not yet connected to the backend, but the deployment steps should succeed.  If they don't please post again.

**Comment by tyg** [comment]
Tried from scratch. It looks like this time it may have made it through deploy, but then got the following on ui:

agoric deploy ./contract/deploy.js ./api/deploy.js
agoric: deploy: Chain loaded: chain bundle loaded
'fs' is imported by contract/deploy.js, but could not be resolved – treating it as an external dependency
- instance made simple-exchange => simple-exchange_9794
writing dappConstants.js
writing /Users/tyg/agoric-sdk/demo/ui/.env.local
agoric: TypeError: target[registerCommandHandler] does not exist, has registerAPIHandler
    at fullRevive (/Users/tyg/agoric-sdk/packages/captp/dist/captp.cjs.js:2455:46)
    at unserialize (/Users/tyg/agoric-sdk/packages/captp/dist/captp.cjs.js:2497:19)
    at CTP_RETURN (/Users/tyg/agoric-sdk/packages/captp/dist/captp.cjs.js:2677:16)
    at dispatch (/Users/tyg/agoric-sdk/packages/captp/dist/captp.cjs.js:2724:7)
    at WebSocket.<anonymous> (/Users/tyg/agoric-sdk/packages/agoric-cli/lib/deploy.js:57:11)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at Receiver.receiverOnMessage (/Users/tyg/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.EventEmitter.emit (domain.js:482:12)
tomgallmacbook2:demo tyg$ 

Also, got this in the other shell:
web: 127.0.0.1:61633[1]: client closed

**Comment by michaelfig** [comment]
The deploy scripts are now working, so please try again.  The getting started guide instructions should work.
