### ISSUE TITLE
agoric deploy fails in current commit

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#735]
I'm at this commit : https://github.com/Agoric/agoric-sdk/tree/00fa052ab6c2f8fcb610cd35bfc2900e49df91aa

I did the getting started steps and at `agoric deploy`, i get:
```sh
agoric: deploy: Chain loaded: chain bundle loaded
'fs' is imported by contract/deploy.js, but could not be resolved – treating it as an external dependency
- instance made simple-exchange => simple-exchange_9794
writing dappConstants.js
writing /tmp/demo/ui/.env.local
agoric: TypeError: target[registerCommandHandler] does not exist, has registerAPIHandler
    at fullRevive (/home/david/projects/agoric-sdk/packages/captp/dist/captp.cjs.js:2455:46)
    at unserialize (/home/david/projects/agoric-sdk/packages/captp/dist/captp.cjs.js:2497:19)
    at CTP_RETURN (/home/david/projects/agoric-sdk/packages/captp/dist/captp.cjs.js:2677:16)
    at dispatch (/home/david/projects/agoric-sdk/packages/captp/dist/captp.cjs.js:2724:7)
    at WebSocket.<anonymous> (/home/david/projects/agoric-sdk/packages/agoric-cli/lib/deploy.js:57:11)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:485:12)
    at Receiver.receiverOnMessage (/home/david/projects/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:485:12)

```

**Comment by michaelfig** [comment]
The demo installation instructions work again (but is not yet working end-to-end).  Please try again.

**Comment by michaelfig** [comment]
This default demo is now working end-to-end.  I'm closing the issue.

#724 will stay open until full end-to-end is added to the agoric-cli workflow tests.
