### ISSUE TITLE
intermittent failure in cosmic-swingset tests during 'make' compilation

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#862]
We noticed an occasional failure of CI that appears to happen during the `make` step that compiles all the Go code in cosmic-swingset. One failing test run is in the `test-cosmic-swingset` job of the test run for #845  here:

https://github.com/Agoric/agoric-sdk/pull/845/checks?check_run_id=564919090

The only unusual parts of the log output I can see is this chunk:

```
github.com/cosmos/cosmos-sdk/crypto/keys/hd
github.com/tendermint/btcd/btcec
# github.com/tendermint/btcd/btcec
##[error]/home/runner/go/pkg/mod/github.com/tendermint/btcd@v0.1.1/btcec/secp256k1.go:10:27: string not terminated
github.com/cosmos/cosmos-sdk/crypto/keys/keyerror
github.com/cosmos/cosmos-sdk/types/errors
github.com/gsterjov/go-libsecret
```

followed by the point where it failed opaquely:

```
github.com/cosmos/cosmos-sdk/x/distribution/legacy/v0_36
github.com/cosmos/cosmos-sdk/x/genaccounts/legacy/v0_34
github.com/cosmos/cosmos-sdk/x/gov/legacy/v0_34
github.com/cosmos/cosmos-sdk/x/staking/legacy/v0_34
github.com/cosmos/cosmos-sdk/x/genaccounts/legacy/v0_36
github.com/cosmos/cosmos-sdk/x/gov/legacy/v0_36
github.com/cosmos/cosmos-sdk/x/staking/legacy/v0_36

    ✖ exits successfully
    ---------------------
      operator: equal
      expected: 0
      actual:   2
      at: ChildProcess.<anonymous> (/home/runner/work/agoric-sdk/agoric-sdk/packages/cosmic-swingset/test/test-make.js:11:11)
      stack: |-
  Error: exits successfully
  at Test.assert [as _assert] (/home/runner/work/agoric-sdk/agoric-sdk/node_modules/tape/lib/test.js:225:54)
  at Test.bound [as _assert] (/home/runner/work/agoric-sdk/agoric-sdk/node_modules/tape/lib/test.js:77:32)
  at Test.equal (/home/runner/work/agoric-sdk/agoric-sdk/node_modules/tape/lib/test.js:385:10)
  at Test.bound [as equal] (/home/runner/work/agoric-sdk/agoric-sdk/node_modules/tape/lib/test.js:77:32)
  at ChildProcess.<anonymous> (/home/runner/work/agoric-sdk/agoric-sdk/packages/cosmic-swingset/test/test-make.js:11:11)
  at ChildProcess.emit (events.js:311:20)
  at ChildProcess.EventEmitter.emit (domain.js:482:12)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)


  Node version

    ✔ we need Node 11 where the IO queue is higher priority than the Promise queue

  make scenario3-setup

github.com/cosmos/cosmos-sdk/x/supply/legacy/v0_36
github.com/cosmos/cosmos-sdk/x/auth/legacy/v0_38
github.com/cosmos/cosmos-sdk/x/distribution/legacy/v0_38
github.com/cosmos/cosmos-sdk/x/staking/legacy/v0_38
github.com/cosmos/cosmos-sdk/x/auth/legacy/v0_39
github.com/cosmos/cosmos-sdk/x/bank/legacy/v0_39
make: *** [compile-go] Error 2
    ✔ exits successfully



  Failed Tests: There was 1 failure

    make

      ✖ exits successfully


  total:     3
  passing:   2
  failing:   1
  duration:  38.1s


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

@Chris-Hibbert tells me he's seen this intermittently before, so I'm going to hit the "rebuild" button to try and fix this particular CI run.

@michaelfig is this enough to give you an idea of what's going wrong, or how to either fix it or add something that lets us learn more in the future?

**Comment by warner** [comment]
it happened again in the rebuild (https://github.com/Agoric/agoric-sdk/pull/845/checks?check_run_id=564919090)  (also, eww, apparently the rebuild gets the same `check_run_id` as the original, so there may be no way to point at a failing run and a re-built run as separate URLs.. in fact the original might be lost entirely):

```
github.com/tendermint/btcd/btcec
# github.com/tendermint/btcd/btcec
##[error]/home/runner/go/pkg/mod/github.com/tendermint/btcd@v0.1.1/btcec/secp256k1.go:10:27: string not terminated
github.com/cosmos/cosmos-sdk/crypto/keys/keyerror
github.com/cosmos/cosmos-sdk/types/errors
```

**Comment by warner** [comment]
Not sure if it's related, but I saw another failure in a different PR (and different step of the build):

```
Set up Go 1.13
26s
##[error]The process '/bin/tar' failed with exit code 2
Run actions/setup-go@v1
/bin/tar xzC /home/runner/work/_temp/2cc9cd35-4b17-4dc0-99be-e2c08bd33301 -f /home/runner/work/_temp/1ef564d9-97c6-4daa-91b1-5eea5dad26d3

gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
##[error]The process '/bin/tar' failed with exit code 2
```

![Screenshot_2020-04-06 fix (still-broken) test of liveslots promise handling by warner · Pull Request #863 · Agoric agoric-sdk](https://user-images.githubusercontent.com/27146/78594710-a1034a00-77fd-11ea-8833-904c2d465f50.png)
