### ISSUE TITLE
agoric deploy failure (likely related to recent PR about zoe helper imports)

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#874]
I followed the getting started steps
and on `agoric deploy`:
```sh
$ agoric deploy ./contract/deploy.js ./api/deploy.js
agoric: deploy: Chain loaded: chain bundle loaded
'@agoric/zoe/src/contracts/helpers/zoeHelpers' is imported by contract/contract.js, but could not be resolved – treating it as an external dependency
agoric: Error: 'default' is not exported by ../../home/david/projects/agoric-sdk/packages/make-promise/src/makePromise.js
    at error (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at handleMissingExport (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:9721:28)
    at Module.traceVariable (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:10159:24)
    at ModuleScope.findVariable (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:8766:39)
    at FunctionScope.findVariable (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at CallExpression$1.bind (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at CallExpression$1.bind (/home/david/projects/agoric-sdk/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:6718:15) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  pos: 87,
  loc: { column: 7, file: '/tmp/demo/contract/zoeNotifier.js', line: 3 },
  frame: "1: import { E } from '@agoric/eventual-send';\n" +
    "2: import harden from '@agoric/harden';\n" +
    "3: import makePromise from '@agoric/make-promise';\n" +
    '          ^\n' +
    "4: import makeStore from '@agoric/store';",
  watchFiles: [
    '/tmp/demo/contract/contract.js',
    '/tmp/demo/contract/zoeNotifier.js',
    '/home/david/projects/agoric-sdk/packages/make-promise/src/makePromise.js',
    '/home/david/projects/agoric-sdk/packages/store/src/store.js',
    '/home/david/projects/agoric-sdk/packages/eventual-send/src/index.js',
    '/home/david/projects/agoric-sdk/packages/eventual-send/src/E.js',
    '/home/david/projects/agoric-sdk/packages/assert/src/assert.js'
  ]
}
```

I guess it's related to #867

I'm failing again to run `agoric deploy`
I'd like to suggest again that getting started steps be added to continuous integration. See #734 #760

**Comment by michaelfig** [comment]
> I'd like to suggest again that getting started steps be added to continuous integration.

I will take your PR as a guide and add it to the `agoric-cli` tests.
