### ISSUE TITLE
`agoric deploy contract/deploy.js` produces a syntax error

### ISSUE THREAD

**Issue by vporton** [Agoric/agoric-sdk#981]
Download https://github.com/vporton/time-release/tree/d5041bdfb354f4911a26de5afbb3d03db6fe2bb0

Do `agoric install`.

In one terminal:
```
agoric start --reset
```

```
$ agoric deploy contract/deploy.js
SecurityWarning: '@agoric/harden' doesn't prevent prototype poisoning without SES
SecurityWarning: '@agoric/harden' doesn't prevent prototype poisoning without SES
agoric: deploy: Open CapTP connection to ws://127.0.0.1:8000/private/captp (try=1)...
agoric: deploy: Connected to CapTP!
agoric: deploy: Chain loaded: chain bundle loaded
agoric: deploy: running /home/porton/Projects/bounties/time-release/contract/deploy.js
agoric: SyntaxError: unknown: Identifier getMeter is reserved for metering code
  79 | 
  80 | 
> 81 |     fullEndowments.getMeter = m => {
     |                    ^^^^^^^^
  82 |       if (m !== true && typeof replaceGlobalMeter !== 'undefined') {
  83 |         // Replace the global meter.
  84 |         replaceGlobalMeter(meter$1);
    at fullRevive (/home/porton/Projects/bounties/agoric-sdk/packages/captp/dist/captp.cjs.js:2653:51)
    at unserialize (/home/porton/Projects/bounties/agoric-sdk/packages/captp/dist/captp.cjs.js:2695:24)
    at CTP_RETURN (/home/porton/Projects/bounties/agoric-sdk/packages/captp/dist/captp.cjs.js:2875:16)
    at dispatch (/home/porton/Projects/bounties/agoric-sdk/packages/captp/dist/captp.cjs.js:2922:7)
    at WebSocket.<anonymous> (/home/porton/Projects/bounties/agoric-sdk/packages/agoric-cli/lib/deploy.js:54:13)
    at WebSocket.emit (events.js:310:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at Receiver.receiverOnMessage (/home/porton/Projects/bounties/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.EventEmitter.emit (domain.js:482:12)
```

**Comment by michaelfig** [comment]
It kinda looks like your deploy script is importing too much (i.e. it's importing code that should only run as part of the chain infrastructure, not as part of a contract).  What imports did you add to it?

**Comment by vporton** [comment]
I didn't add any imports to it, **only** changed the contract it loads.

**Comment by vporton** [comment]
Moreover, at my best memory, I only changed the contracts and the deploy script to use a new contract, and nothing other in the source after cloning the template.

**Comment by michaelfig** [comment]
We worked past this.  It turns out @vporton was accidentally creating a new Zoe instance, and they don't nest in the current implementation.  https://github.com/vporton/time-release/blob/d5041bdfb354f4911a26de5afbb3d03db6fe2bb0/contract/src/contracts/time-release.js#L13
